-- Authoritative: runtime SQLite snapshot + database.js complete schema.
-- scheduled_time intentionally stays TEXT: legacy local/UTC values are not reinterpreted.
CREATE TABLE candidates (
      id TEXT PRIMARY KEY,
      full_name TEXT NOT NULL,
      email TEXT NOT NULL,
      phone_number TEXT,
      requisition_id TEXT ,
      stage TEXT NOT NULL DEFAULT 'NEW',
      experience_years INTEGER NOT NULL DEFAULT 1,
      current_company TEXT,
      expected_salary TEXT,
      notes TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    , source_id TEXT , rejection_reason_id TEXT );

CREATE TABLE career_page_settings (
      id INTEGER PRIMARY KEY CHECK (id = 1),
      introduction TEXT NOT NULL DEFAULT '',
      logo_url TEXT,
      hero_image_url TEXT,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE competency_criteria (
      id TEXT PRIMARY KEY,
      framework_id TEXT NOT NULL
        ,
      name TEXT NOT NULL,
      description TEXT,
      weight INTEGER NOT NULL
        CHECK (weight > 0 AND weight <= 100),
      display_order INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE competency_frameworks (
      id TEXT PRIMARY KEY,
      code TEXT UNIQUE NOT NULL,
      name TEXT NOT NULL,
      description TEXT,
      status TEXT NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'INACTIVE')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE departments (
      id TEXT PRIMARY KEY,
      code TEXT UNIQUE NOT NULL,
      name TEXT NOT NULL,
      parent_id TEXT ,
      manager_id TEXT NOT NULL ,
      status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE email_logs (
      id TEXT PRIMARY KEY,
      recipient TEXT NOT NULL,
      subject TEXT NOT NULL,
      template_name TEXT NOT NULL,
      status TEXT NOT NULL,
      error_message TEXT,
      sent_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE interview_questions (
      id TEXT PRIMARY KEY,
      criterion_id TEXT NOT NULL
        ,
      question_text TEXT NOT NULL,
      difficulty TEXT NOT NULL
        CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
      good_answer_hint TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'INACTIVE')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE interviews (
      id TEXT PRIMARY KEY,
      candidate_id TEXT ,
      requisition_id TEXT ,
      interviewer_id TEXT ,
      round_name TEXT NOT NULL DEFAULT 'Phỏng vấn chuyên môn',
      scheduled_time TEXT NOT NULL,
      location_or_link TEXT,
      status TEXT NOT NULL DEFAULT 'SCHEDULED',
      feedback TEXT,
      score INTEGER,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE job_titles (
      id TEXT PRIMARY KEY,
      code TEXT UNIQUE NOT NULL,
      name TEXT NOT NULL,
      framework_id TEXT
        ,
      level TEXT,
      min_salary NUMERIC CHECK (min_salary IS NULL OR min_salary >= 0),
      max_salary NUMERIC CHECK (max_salary IS NULL OR max_salary >= min_salary),
      status TEXT NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'INACTIVE')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE login_audit_logs (
      sequence_id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
      id TEXT PRIMARY KEY,
      email TEXT NOT NULL,
      ip_address TEXT,
      status TEXT NOT NULL,
      reason TEXT,
      attempted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE offers (
      id TEXT PRIMARY KEY,
      candidate_id TEXT ,
      requisition_id TEXT ,
      salary_monthly NUMERIC NOT NULL,
      start_date DATE NOT NULL,
      status TEXT NOT NULL DEFAULT 'PENDING_APPROVAL',
      approver_id TEXT ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE otps (
      id TEXT PRIMARY KEY,
      email TEXT NOT NULL,
      otp_code TEXT NOT NULL,
      purpose TEXT NOT NULL DEFAULT 'PASSWORD_RESET',
      expires_at TIMESTAMPTZ NOT NULL,
      verified_at TIMESTAMPTZ,
      used_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE password_reset_tokens (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL ,
      token TEXT UNIQUE NOT NULL,
      expires_at TIMESTAMPTZ NOT NULL,
      used_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE permissions (
      id TEXT PRIMARY KEY,
      code TEXT UNIQUE NOT NULL,
      name TEXT NOT NULL,
      module TEXT NOT NULL,
      description TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE recruitment_catalog_items (
      id TEXT PRIMARY KEY,
      type TEXT NOT NULL
        CHECK (type IN ('CANDIDATE_SOURCE', 'REJECTION_REASON', 'WORK_LOCATION', 'WORK_MODE')),
      code TEXT NOT NULL,
      name TEXT NOT NULL,
      display_order INTEGER NOT NULL DEFAULT 0,
      status TEXT NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'INACTIVE')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(type, code)
    );

CREATE TABLE requisitions (
      id TEXT PRIMARY KEY,
      code TEXT UNIQUE NOT NULL,
      title TEXT NOT NULL,
      job_title_id TEXT ,
      department_id TEXT ,
      work_location_id TEXT ,
      work_mode_id TEXT ,
      department_name TEXT NOT NULL,
      hiring_manager_id TEXT ,
      recruiter_id TEXT ,
      status TEXT NOT NULL DEFAULT 'OPEN',
      headcount INTEGER NOT NULL DEFAULT 1,
      handover_required BOOLEAN NOT NULL DEFAULT FALSE,
      handover_notes TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    , s210_version INTEGER NOT NULL DEFAULT 0, created_by TEXT , recruitment_reason TEXT CHECK (recruitment_reason IS NULL OR recruitment_reason IN ('REPLACEMENT', 'NEW_HEADCOUNT')), proposed_salary_min NUMERIC CHECK (proposed_salary_min IS NULL OR proposed_salary_min >= 0), proposed_salary_max NUMERIC CHECK (proposed_salary_max IS NULL OR (proposed_salary_max >= 0 AND proposed_salary_max >= proposed_salary_min)), needed_date DATE, job_description TEXT, candidate_requirements TEXT, salary_justification TEXT);

CREATE TABLE role_permissions (
      role_id TEXT NOT NULL ,
      permission_id TEXT NOT NULL ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (role_id, permission_id)
    );

CREATE TABLE roles (
      id TEXT PRIMARY KEY,
      code TEXT UNIQUE NOT NULL,
      name TEXT NOT NULL,
      description TEXT,
      default_path TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE sessions (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL ,
      token TEXT UNIQUE NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      expires_at TIMESTAMPTZ NOT NULL,
      last_activity_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE user_roles (
      user_id TEXT NOT NULL ,
      role_id TEXT NOT NULL ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (user_id, role_id)
    );

CREATE TABLE users (
      id TEXT PRIMARY KEY,
      email TEXT UNIQUE NOT NULL,
      password_hash TEXT NOT NULL,
      full_name TEXT NOT NULL,
      job_title TEXT,
      department_id TEXT,
      department_name TEXT,
      phone_number TEXT,
      status TEXT NOT NULL DEFAULT 'ACTIVE',
      lock_reason TEXT,
      failed_attempts INTEGER NOT NULL DEFAULT 0,
      must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
      locked_until TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

ALTER TABLE candidates ADD CONSTRAINT fk_candidates_rejection_reason_id FOREIGN KEY (rejection_reason_id) REFERENCES recruitment_catalog_items (id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE candidates ADD CONSTRAINT fk_candidates_source_id FOREIGN KEY (source_id) REFERENCES recruitment_catalog_items (id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE candidates ADD CONSTRAINT fk_candidates_requisition_id FOREIGN KEY (requisition_id) REFERENCES requisitions (id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE competency_criteria ADD CONSTRAINT fk_competency_criteria_framework_id FOREIGN KEY (framework_id) REFERENCES competency_frameworks (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE departments ADD CONSTRAINT fk_departments_manager_id FOREIGN KEY (manager_id) REFERENCES users (id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE departments ADD CONSTRAINT fk_departments_parent_id FOREIGN KEY (parent_id) REFERENCES departments (id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE interview_questions ADD CONSTRAINT fk_interview_questions_criterion_id FOREIGN KEY (criterion_id) REFERENCES competency_criteria (id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE interviews ADD CONSTRAINT fk_interviews_interviewer_id FOREIGN KEY (interviewer_id) REFERENCES users (id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE interviews ADD CONSTRAINT fk_interviews_requisition_id FOREIGN KEY (requisition_id) REFERENCES requisitions (id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE interviews ADD CONSTRAINT fk_interviews_candidate_id FOREIGN KEY (candidate_id) REFERENCES candidates (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE job_titles ADD CONSTRAINT fk_job_titles_framework_id FOREIGN KEY (framework_id) REFERENCES competency_frameworks (id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE offers ADD CONSTRAINT fk_offers_approver_id FOREIGN KEY (approver_id) REFERENCES users (id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE offers ADD CONSTRAINT fk_offers_requisition_id FOREIGN KEY (requisition_id) REFERENCES requisitions (id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE offers ADD CONSTRAINT fk_offers_candidate_id FOREIGN KEY (candidate_id) REFERENCES candidates (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE password_reset_tokens ADD CONSTRAINT fk_password_reset_tokens_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE requisitions ADD CONSTRAINT fk_requisitions_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE requisitions ADD CONSTRAINT fk_requisitions_recruiter_id FOREIGN KEY (recruiter_id) REFERENCES users (id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE requisitions ADD CONSTRAINT fk_requisitions_hiring_manager_id FOREIGN KEY (hiring_manager_id) REFERENCES users (id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE requisitions ADD CONSTRAINT fk_requisitions_work_mode_id FOREIGN KEY (work_mode_id) REFERENCES recruitment_catalog_items (id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE requisitions ADD CONSTRAINT fk_requisitions_work_location_id FOREIGN KEY (work_location_id) REFERENCES recruitment_catalog_items (id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE requisitions ADD CONSTRAINT fk_requisitions_department_id FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE requisitions ADD CONSTRAINT fk_requisitions_job_title_id FOREIGN KEY (job_title_id) REFERENCES job_titles (id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE role_permissions ADD CONSTRAINT fk_role_permissions_permission_id FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE role_permissions ADD CONSTRAINT fk_role_permissions_role_id FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE sessions ADD CONSTRAINT fk_sessions_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE user_roles ADD CONSTRAINT fk_user_roles_role_id FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE user_roles ADD CONSTRAINT fk_user_roles_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE users ADD CONSTRAINT fk_users_department FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_candidates_requisition ON candidates(requisition_id);

CREATE INDEX idx_candidates_stage ON candidates(stage);

CREATE INDEX idx_candidates_source
      ON candidates(source_id);

CREATE INDEX idx_candidates_rejection_reason
      ON candidates(rejection_reason_id);

CREATE INDEX idx_competency_criteria_framework
      ON competency_criteria(framework_id);

CREATE INDEX idx_departments_parent ON departments(parent_id);

CREATE INDEX idx_departments_manager ON departments(manager_id);

CREATE INDEX idx_departments_status ON departments(status);

CREATE INDEX idx_email_logs_recipient ON email_logs(recipient);

CREATE INDEX idx_interview_questions_criterion
      ON interview_questions(criterion_id);

CREATE INDEX idx_interview_questions_difficulty
      ON interview_questions(difficulty);

CREATE INDEX idx_interview_questions_status
      ON interview_questions(status);

CREATE INDEX idx_interviews_candidate ON interviews(candidate_id);

CREATE INDEX idx_interviews_interviewer ON interviews(interviewer_id);

CREATE INDEX idx_job_titles_framework
      ON job_titles(framework_id);

CREATE INDEX idx_job_titles_status
      ON job_titles(status);

CREATE INDEX idx_audit_email ON login_audit_logs(email);

CREATE INDEX idx_offers_candidate ON offers(candidate_id);

CREATE INDEX idx_otps_email ON otps(email);

CREATE INDEX idx_reset_token ON password_reset_tokens(token);

CREATE INDEX idx_permissions_code ON permissions(code);

CREATE INDEX idx_recruitment_catalog_type_order
      ON recruitment_catalog_items(type, display_order);

CREATE INDEX idx_requisitions_recruiter ON requisitions(recruiter_id);

CREATE INDEX idx_requisitions_hiring_mgr ON requisitions(hiring_manager_id);

CREATE INDEX idx_requisitions_status ON requisitions(status);

CREATE INDEX idx_requisitions_department ON requisitions(department_id);

CREATE INDEX idx_requisitions_job_title ON requisitions(job_title_id);

CREATE INDEX idx_requisitions_work_location
      ON requisitions(work_location_id);

CREATE INDEX idx_requisitions_work_mode
      ON requisitions(work_mode_id);

CREATE INDEX idx_role_permissions_role ON role_permissions(role_id);

CREATE INDEX idx_role_permissions_perm ON role_permissions(permission_id);

CREATE INDEX idx_roles_code ON roles(code);

CREATE INDEX idx_sessions_token ON sessions(token);

CREATE INDEX idx_user_roles_user ON user_roles(user_id);

CREATE INDEX idx_users_email ON users(email);

CREATE UNIQUE INDEX users_email_ci_unique ON users(lower(email));

CREATE INDEX login_audit_email_sequence ON login_audit_logs(lower(email), sequence_id DESC);
