CREATE TABLE headcount_budgets (id TEXT PRIMARY KEY,department_id TEXT NOT NULL REFERENCES departments(id),budget_year INTEGER NOT NULL CHECK(budget_year BETWEEN 1000 AND 9999),current_version_id TEXT REFERENCES headcount_budget_versions(id) DEFERRABLE INITIALLY DEFERRED,UNIQUE(department_id,budget_year));
CREATE TABLE headcount_budget_versions (id TEXT PRIMARY KEY,budget_id TEXT NOT NULL REFERENCES headcount_budgets(id),version_number INTEGER NOT NULL CHECK(version_number>0),approved_headcount INTEGER NOT NULL CHECK(approved_headcount>=0),annual_salary_budget NUMERIC NOT NULL CHECK(annual_salary_budget>=0),actor_id TEXT NOT NULL,actor_name TEXT NOT NULL,reason TEXT,created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),UNIQUE(budget_id,version_number));

CREATE TABLE headcount_budget_participation (requisition_id TEXT PRIMARY KEY REFERENCES requisitions(id),approved INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')));
CREATE TABLE headcount_budget_reservations (requisition_id TEXT PRIMARY KEY REFERENCES requisitions(id),department_id TEXT NOT NULL REFERENCES departments(id),budget_year INTEGER NOT NULL,headcount_delta INTEGER NOT NULL CHECK(headcount_delta>=0),salary_delta NUMERIC NOT NULL CHECK(salary_delta>=0),replaces_unapproved INTEGER NOT NULL DEFAULT 0 CHECK(replaces_unapproved IN (0,1)),content_hash TEXT NOT NULL,submission_id TEXT NOT NULL REFERENCES requisition_approval_submissions(id),created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')));
CREATE INDEX headcount_reservation_budget ON headcount_budget_reservations(department_id,budget_year);
CREATE TABLE headcount_budget_exceptions (id TEXT PRIMARY KEY,requisition_id TEXT NOT NULL REFERENCES requisitions(id),department_id TEXT NOT NULL REFERENCES departments(id),budget_year INTEGER NOT NULL,version_id TEXT NOT NULL REFERENCES headcount_budget_versions(id),content_hash TEXT NOT NULL,headcount_over INTEGER NOT NULL CHECK(headcount_over>=0),salary_over NUMERIC NOT NULL CHECK(salary_over>=0),confirmed_by TEXT NOT NULL,confirmed_name TEXT NOT NULL,reason TEXT NOT NULL CHECK(length(trim(reason))>0),created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')));
CREATE INDEX headcount_exception_lookup ON headcount_budget_exceptions(requisition_id,content_hash,version_id);
CREATE TRIGGER headcount_budget_versions_no_update BEFORE UPDATE ON headcount_budget_versions BEGIN SELECT RAISE(ABORT,'BUDGET_HISTORY_IMMUTABLE'); END;
CREATE TRIGGER headcount_budget_versions_no_delete BEFORE DELETE ON headcount_budget_versions BEGIN SELECT RAISE(ABORT,'BUDGET_HISTORY_IMMUTABLE'); END;
CREATE TRIGGER headcount_budget_exceptions_no_update BEFORE UPDATE ON headcount_budget_exceptions BEGIN SELECT RAISE(ABORT,'BUDGET_HISTORY_IMMUTABLE'); END;
CREATE TRIGGER headcount_budget_exceptions_no_delete BEFORE DELETE ON headcount_budget_exceptions BEGIN SELECT RAISE(ABORT,'BUDGET_HISTORY_IMMUTABLE'); END;
