CREATE TABLE requisition_lifecycle_events(id TEXT PRIMARY KEY,requisition_id TEXT NOT NULL REFERENCES requisitions(id),version INTEGER NOT NULL CHECK(version>0),before_status TEXT NOT NULL,after_status TEXT NOT NULL,action TEXT NOT NULL CHECK(action IN ('FULFILLED','PAUSED','CANCELLED')),reason TEXT NOT NULL CHECK(length(trim(reason))>0),actor_id TEXT NOT NULL,actor_name TEXT NOT NULL,request_id TEXT NOT NULL,fingerprint TEXT NOT NULL,pipeline_json TEXT NOT NULL,budget_json TEXT NOT NULL,postings_json TEXT NOT NULL,response_json TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(requisition_id,version),UNIQUE(actor_id,request_id));
CREATE TABLE requisition_lifecycle_state(requisition_id TEXT PRIMARY KEY REFERENCES requisitions(id),version INTEGER NOT NULL CHECK(version>0),last_event_id TEXT NOT NULL REFERENCES requisition_lifecycle_events(id));
CREATE INDEX lifecycle_events_requisition ON requisition_lifecycle_events(requisition_id,version);
CREATE TABLE job_postings(id TEXT PRIMARY KEY,requisition_id TEXT NOT NULL REFERENCES requisitions(id),title TEXT NOT NULL,job_description TEXT NOT NULL DEFAULT '',candidate_requirements TEXT NOT NULL DEFAULT '',status TEXT NOT NULL CHECK(status IN ('DRAFT','PUBLISHED','PAUSED','UNPUBLISHED')),published_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX job_postings_requisition ON job_postings(requisition_id,status);
CREATE INDEX job_postings_public ON job_postings(status,published_at,id);
CREATE FUNCTION lifecycle_history_guard() RETURNS TRIGGER LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'LIFECYCLE_HISTORY_IMMUTABLE';END;$$;
CREATE TRIGGER lifecycle_events_immutable BEFORE UPDATE OR DELETE ON requisition_lifecycle_events FOR EACH ROW EXECUTE FUNCTION lifecycle_history_guard();
CREATE TRIGGER lifecycle_events_no_truncate BEFORE TRUNCATE ON requisition_lifecycle_events FOR EACH STATEMENT EXECUTE FUNCTION lifecycle_history_guard();
