ALTER TABLE requisitions ADD COLUMN opened_at TEXT;
ALTER TABLE job_postings ADD COLUMN work_location_id TEXT REFERENCES recruitment_catalog_items(id);
ALTER TABLE job_postings ADD COLUMN work_mode_id TEXT REFERENCES recruitment_catalog_items(id);
ALTER TABLE job_postings ADD COLUMN application_deadline TEXT;
ALTER TABLE job_postings ADD COLUMN show_salary INTEGER NOT NULL DEFAULT 0 CHECK(show_salary IN (0,1));
ALTER TABLE job_postings ADD COLUMN salary_min REAL;
ALTER TABLE job_postings ADD COLUMN salary_max REAL;
ALTER TABLE job_postings ADD COLUMN source_submission_id TEXT REFERENCES requisition_approval_submissions(id);
ALTER TABLE job_postings ADD COLUMN source_content_hash TEXT;
ALTER TABLE job_postings ADD COLUMN version INTEGER NOT NULL DEFAULT 0 CHECK(version>=0);
ALTER TABLE job_postings ADD COLUMN created_by TEXT;
ALTER TABLE job_postings ADD COLUMN updated_by TEXT;
CREATE TABLE job_posting_draft_requests(actor_id TEXT NOT NULL,request_id TEXT NOT NULL,fingerprint TEXT NOT NULL,response_json TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')),PRIMARY KEY(actor_id,request_id));
CREATE INDEX requisition_tracking_created ON requisitions(created_at,id);
CREATE INDEX job_posting_draft_source ON job_postings(requisition_id,status,id);
CREATE TRIGGER requisition_first_open_insert AFTER INSERT ON requisitions WHEN NEW.status='OPEN' AND NEW.opened_at IS NULL BEGIN UPDATE requisitions SET opened_at=datetime('now') WHERE id=NEW.id;END;
CREATE TRIGGER requisition_first_open_update AFTER UPDATE OF status ON requisitions WHEN OLD.status='DRAFT' AND NEW.status='OPEN' AND NEW.opened_at IS NULL BEGIN UPDATE requisitions SET opened_at=datetime('now') WHERE id=NEW.id;END;
CREATE TRIGGER job_draft_requests_no_update BEFORE UPDATE ON job_posting_draft_requests BEGIN SELECT RAISE(ABORT,'JOB_DRAFT_RECEIPT_IMMUTABLE');END;
CREATE TRIGGER job_draft_requests_no_delete BEFORE DELETE ON job_posting_draft_requests BEGIN SELECT RAISE(ABORT,'JOB_DRAFT_RECEIPT_IMMUTABLE');END;
