ALTER TABLE requisitions ADD COLUMN opened_at TIMESTAMPTZ;
ALTER TABLE job_postings ADD COLUMN work_location_id TEXT REFERENCES recruitment_catalog_items(id);
ALTER TABLE job_postings ADD COLUMN work_mode_id TEXT REFERENCES recruitment_catalog_items(id);
ALTER TABLE job_postings ADD COLUMN application_deadline DATE;
ALTER TABLE job_postings ADD COLUMN show_salary BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE job_postings ADD COLUMN salary_min NUMERIC;
ALTER TABLE job_postings ADD COLUMN salary_max NUMERIC;
ALTER TABLE job_postings ADD COLUMN source_submission_id TEXT REFERENCES requisition_approval_submissions(id);
ALTER TABLE job_postings ADD COLUMN source_content_hash TEXT;
ALTER TABLE job_postings ADD COLUMN version INTEGER NOT NULL DEFAULT 0 CHECK(version>=0);
ALTER TABLE job_postings ADD COLUMN created_by TEXT;
ALTER TABLE job_postings ADD COLUMN updated_by TEXT;
CREATE TABLE job_posting_draft_requests(actor_id TEXT NOT NULL,request_id TEXT NOT NULL,fingerprint TEXT NOT NULL,response_json TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(actor_id,request_id));
CREATE INDEX requisition_tracking_created ON requisitions(created_at,id);
CREATE INDEX job_posting_draft_source ON job_postings(requisition_id,status,id);
CREATE FUNCTION requisition_first_open_guard() RETURNS TRIGGER LANGUAGE plpgsql AS $$ BEGIN IF NEW.status='OPEN' AND NEW.opened_at IS NULL AND (TG_OP='INSERT' OR OLD.status='DRAFT') THEN NEW.opened_at=CURRENT_TIMESTAMP;END IF;RETURN NEW;END;$$;
CREATE TRIGGER requisition_first_open BEFORE INSERT OR UPDATE OF status ON requisitions FOR EACH ROW EXECUTE FUNCTION requisition_first_open_guard();
CREATE FUNCTION job_draft_receipt_guard() RETURNS TRIGGER LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'JOB_DRAFT_RECEIPT_IMMUTABLE';END;$$;
CREATE TRIGGER job_draft_receipts_immutable BEFORE UPDATE OR DELETE ON job_posting_draft_requests FOR EACH ROW EXECUTE FUNCTION job_draft_receipt_guard();
CREATE TRIGGER job_draft_receipts_no_truncate BEFORE TRUNCATE ON job_posting_draft_requests FOR EACH STATEMENT EXECUTE FUNCTION job_draft_receipt_guard();
