(function(){
 const get=id=>document.getElementById(id),element=(tag,text)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;return node;},request=(path='',method='GET',body)=>window.ATS_API.headcountBudgetRequestApi(sessionStorage.getItem('ats_token'),path,method,body);
 let generation=0,busy=false,selected=null,createId=null,revisionId=null;const previewGeneration=new Map(),plans=new Map();let timer=null;
 const managed=()=>currentAuthenticatedUser?.roles?.some(role=>['ADMIN','HR_MANAGER'].includes(role));
 const error=text=>{get('s304-message').textContent=text||'';get('s304-alert').classList.toggle('hidden',!text);};
 const year=()=>Number(get('s304-year').value);
 async function details(){const current=++generation,token=sessionStorage.getItem('ats_token'),departmentId=get('s304-department').value;if(!departmentId)return;get('s304-history').textContent='Đang tải…';const query='?'+new URLSearchParams({departmentId,year:year()}),[availability,history]=await Promise.all([request('/availability'+query),request('/history'+query)]);if(current!==generation||token!==sessionStorage.getItem('ats_token'))return;if(!availability.ok||!history.ok){error((!availability.ok?availability:history).data.message);get('s304-history').textContent='';selected=null;return;}selected=availability.data.data;get('s304-usage').textContent=selected.configured?'Còn '+selected.remainingHeadcount+' headcount; còn '+selected.remainingSalary+' VND. Giữ thêm: '+selected.reservedHeadcount+' headcount / '+selected.reservedSalary+' VND.':'Chưa khai báo chỉ tiêu cho phòng ban/năm này.';get('s304-headcount').value=selected.approvedHeadcount??'';get('s304-salary').value=selected.annualSalaryBudget??'';get('s304-history').textContent=[...history.data.data.versions.map(row=>'Phiên bản '+row.version+': '+row.approvedHeadcount+' headcount / '+row.annualSalaryBudget+' VND — '+row.actorName+' — '+(window.ATS_DATETIME?.formatUtcTimestamp?.(row.createdAt)||row.createdAt)+(row.reason?' — '+row.reason:'')),...history.data.data.exceptions.map(row=>'Ngoại lệ '+row.requisitionId+': vượt '+row.headcountOver+' headcount / '+row.salaryOver+' VND — '+row.confirmedName+' — '+(window.ATS_DATETIME?.formatUtcTimestamp?.(row.createdAt)||row.createdAt)+' — '+row.reason)].join('\n\n');}
 async function load(){const current=++generation,token=sessionStorage.getItem('ats_token');error('');get('s304-list').textContent='';get('s304-history').textContent='';selected=null;if(!get('s304-year').value)get('s304-year').value=new Date().getFullYear();const [options,list]=await Promise.all([request('/options'),request('?year='+year())]);if(current!==generation||token!==sessionStorage.getItem('ats_token'))return;if(!options.ok||!list.ok){error((!options.ok?options:list).data.message);return;}const previous=get('s304-department').value;get('s304-department').textContent='';for(const item of options.data.data){const option=element('option',item.name);option.value=item.id;get('s304-department').appendChild(option);}get('s304-department').value=options.data.data.some(item=>item.id===previous)?previous:options.data.data[0]?.id||'';for(const item of list.data.data){const row=element('tr');for(const value of [item.departmentName,item.version,item.approvedHeadcount,item.annualSalaryBudget])row.appendChild(element('td',String(value)));get('s304-list').appendChild(row);}if(!list.data.data.length){const row=element('tr'),cell=element('td','Chưa có chỉ tiêu cho năm này.');cell.colSpan=4;row.appendChild(cell);get('s304-list').appendChild(row);}get('s304-form').classList.toggle('hidden',!managed());get('s304-exception-form').classList.toggle('hidden',!managed());await details();}
 async function mutate(action){if(busy)return;busy=true;get('s304-save').disabled=true;get('s304-exception-save').disabled=true;const current=generation,token=sessionStorage.getItem('ats_token');error('');try{const result=await action();if(current!==generation||token!==sessionStorage.getItem('ats_token'))return;if(!result.ok){error(result.data.message);return;}await load();showToast('success','Ngân sách','Đã ghi nhận và giữ lịch sử thay đổi.');}finally{busy=false;get('s304-save').disabled=false;get('s304-exception-save').disabled=false;}}
 get('s304-form')?.addEventListener('submit',event=>{event.preventDefault();return mutate(()=>request('','POST',{departmentId:get('s304-department').value,year:year(),approvedHeadcount:Number(get('s304-headcount').value),annualSalaryBudget:Number(get('s304-salary').value),reason:get('s304-change-reason').value,...(selected?.configured?{expectedVersion:selected.version}:{})}));});
 get('s304-exception-form')?.addEventListener('submit',event=>{event.preventDefault();return mutate(async()=>{const token=sessionStorage.getItem('ats_token'),current=generation,reason=get('s304-exception-reason').value,document={departmentId:get('s304-department').value,headcount:get('s304-exception-count').value,proposedSalaryMax:get('s304-exception-max').value,neededDate:get('s304-exception-date').value},requisitionId=get('s304-exception-id').value,availability=await request('/availability?'+new URLSearchParams({...document,requisitionId}));if(!availability.ok)return availability;if(token!==sessionStorage.getItem('ats_token')||current!==generation)return {ok:false,data:{message:'Phiên hoặc biểu mẫu đã thay đổi.'}};return request('/exceptions','POST',{requisitionId,document,reason,expectedVersion:availability.data.data.version});});});
 get('s304-refresh')?.addEventListener('click',load);get('s304-year')?.addEventListener('change',load);get('s304-department')?.addEventListener('change',details);
 const sources={create:()=>({departmentId:get('create-req-dept-input').value,headcount:get('create-req-headcount-input').value,proposedSalaryMax:get('create-req-salary-max-input').value,neededDate:get('create-req-needed-date-input').value}),revision:()=>({departmentId:get('s302-department').value,headcount:get('s302-quantity').value,proposedSalaryMax:get('s302-max').value,neededDate:get('s302-needed').value})};
 async function preview(kind){const prefix='s304-'+kind,panel=get(prefix+'-panel');if(!panel)return;const revision=(previewGeneration.get(kind)||0)+1;previewGeneration.set(kind,revision);const token=sessionStorage.getItem('ats_token'),data=sources[kind](),id=kind==='create'?createId:revisionId;get(prefix+'-override').classList.add('hidden');if(!currentAuthenticatedUser?.permissions?.includes('headcount_budget.read')||!data.departmentId||!data.neededDate){panel.classList.add('hidden');return;}panel.classList.remove('hidden');get(prefix+'-message').textContent='Đang kiểm tra chỉ tiêu…';const query=new URLSearchParams({...data,...(id?{requisitionId:id}:{})}),result=await request('/availability?'+query);if(revision!==previewGeneration.get(kind)||token!==sessionStorage.getItem('ats_token'))return;if(result.data?.code==='S304_DISABLED'){panel.classList.add('hidden');return;}if(!result.ok){get(prefix+'-message').textContent=result.data.message;plans.delete(kind);return;}const value=result.data.data;plans.set(kind,{value,data,id});get(prefix+'-message').textContent=!value.configured?'Chưa có ngân sách cho năm của ngày cần người. Lưu nháp được; hoàn tất/gửi duyệt sẽ bị chặn.':'Còn '+value.remainingHeadcount+' headcount / '+value.remainingSalary+' VND'+(value.projection?' · dự toán '+value.projection.months+' tháng: '+value.projection.annualCost+' VND.':'');if(value.projection&&(value.projection.headcountOver||value.projection.salaryOver)){get(prefix+'-message').textContent+=' Vượt chỉ tiêu/ngân sách, cần HR Manager/Admin xác nhận ngoại lệ. Chưa có dữ liệu được áp dụng.';get(prefix+'-override').classList.toggle('hidden',!id||!managed());}}
 for(const kind of ['create','revision'])get('s304-'+kind+'-confirm')?.addEventListener('click',async()=>{const plan=plans.get(kind),button=get('s304-'+kind+'-confirm');if(!plan||button.disabled)return;if(JSON.stringify(plan.data)!==JSON.stringify(sources[kind]())){get('s304-'+kind+'-message').textContent='Thông tin đã thay đổi. Hãy kiểm tra lại chỉ tiêu trước khi xác nhận.';return;}const reason=get('s304-'+kind+'-reason').value;if(!reason.trim()){get('s304-'+kind+'-message').textContent='Vui lòng nhập lý do ngoại lệ.';return;}button.disabled=true;const token=sessionStorage.getItem('ats_token');try{const result=await request('/exceptions','POST',{requisitionId:plan.id,document:plan.data,expectedVersion:plan.value.version,reason});if(token!==sessionStorage.getItem('ats_token'))return;get('s304-'+kind+'-message').textContent=result.ok?'Đã ghi nhận ngoại lệ. Bạn vẫn cần lưu hoặc gửi hồ sơ riêng.':result.data.message;}finally{button.disabled=false;}});
 const inputs={create:['create-req-dept-input','create-req-headcount-input','create-req-salary-max-input','create-req-needed-date-input'],revision:['s302-department','s302-quantity','s302-max','s302-needed']};for(const [kind,ids]of Object.entries(inputs))for(const id of ids)get(id)?.addEventListener('input',()=>{if(timer)clearTimeout(timer);timer=setTimeout(()=>preview(kind),250);});
 function openCreate(id){createId=id||null;get('s304-create-reason').value='';return preview('create');}
 function openRevision(id){revisionId=id||null;get('s304-revision-reason').value='';return preview('revision');}
 function leave(){generation++;if(timer)clearTimeout(timer);for(const kind of ['create','revision']){previewGeneration.set(kind,(previewGeneration.get(kind)||0)+1);get('s304-'+kind+'-panel')?.classList.add('hidden');}plans.clear();selected=null;createId=null;revisionId=null;get('s304-history').textContent='';get('s304-list').textContent='';}
 window.ATS_HEADCOUNT_BUDGET_UI={load,details,openCreate,openRevision,preview,leave};
})();
