const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),vm=require('node:vm');
const root=path.resolve(__dirname,'../..');
for(const file of ['.git','.env','backend/data/ats.db','backend/data/ats.db-shm','backend/data/ats.db-wal','backend/data/ats_test.db'])assert.equal(fs.existsSync(path.join(root,file)),false,'Fresh isolated copy required');
for(const name of Object.keys(process.env))if(/^(ATS_POSTGRES_|SMTP_|MAIL_|GOOGLE_OAUTH_|DATABASE_|DB_|PG|EMAIL_|APPROVAL_|REQUISITION_APPROVAL_)/.test(name))delete process.env[name];
Object.assign(process.env,{NODE_ENV:'test',DB_PROVIDER:'sqlite',EMAIL_MODE:'simulated'});
const {openApplication}=require('./helpers/coverageApplication'),Requisitions=require('../src/services/requisitionService'),Approvals=require('../src/services/requisitionApprovalService'),Configurations=require('../src/services/approvalConfigurationService').ApprovalConfigurationService;
let passed=0,failed=0;const key=()=>crypto.randomUUID();
async function test(name,action){try{await action();passed++;console.log('[PASS] '+name);}catch(error){failed++;console.error('[FAIL] '+name+'\n'+error.stack);}}
async function cases(db,label){
 await require('../src/db/migrate-approval-configurations').migrate(db);await require('../src/db/migrate-requisition-approvals').migrate(db);
 const reqs=new Requisitions(db),service=new Approvals(db),configs=new Configurations(db),auth=new(require('../src/services/authService'))(db),users={};
 for(const [role,email]of Object.entries({ADMIN:'admin@company.com',HR_MANAGER:'hrmanager@company.com',HIRING_MGR:'hiringmgr@company.com',APPROVER:'approver@company.com',RECRUITER:'recruiter@company.com',INTERVIEWER:'interviewer@company.com',CANDIDATE:'candidate@example.com'}))users[role]=(await auth.login(email,'Ats@123456')).data.user;
 const owner=users.HIRING_MGR,hr=users.HR_MANAGER,admin=users.ADMIN,approver=users.APPROVER;
 const title=await new(require('../src/services/competencyService'))(db).createJobTitle({code:'REA-'+label.replace(/\W/g,''),name:'Reapproval title',level:'Senior',minSalary:10000000,maxSalary:50000000});assert.equal(title.success,true);
 const valid={formVersion:'S2-10',jobTitleId:title.data.id,departmentId:'dept-3',headcount:2,recruitmentReason:'REPLACEMENT',proposedSalaryMin:15000000,proposedSalaryMax:30000000,neededDate:reqs.businessDate(),jobDescription:'Effective JD',candidateRequirements:'Effective requirements',recruiterId:'usr-recruiter'};
 for(const departmentId of ['dept-3','dept-2','dept-4']){let config=await configs.create({departmentId,levels:[{order:1,salaryLimit:20000000,approverUserId:hr.id},{order:2,salaryLimit:60000000,approverUserId:approver.id}]},hr.id);await configs.publish(config.id,config.versions[0].id,hr.id);}
 const create=async(changes={},actor=owner)=>{const result=await reqs.createRequisition({...valid,...changes},actor);assert.equal(result.success,true);return result.data.id;};
 const action=async(id,action='APPROVE',comment='',requestId=key())=>{const detail=await service.read(id,owner),step=detail.steps.find(item=>item.status==='PENDING'),user=Object.values(users).find(item=>item.id===step.approver_id);return service.decide(id,{requestId,action,comment,expectedVersion:detail.version,expectedStepId:step.id},user);};
 const finish=async id=>{while((await service.read(id,owner)).status==='PENDING')await action(id);return service.read(id,owner);};
 const start=async(changes={})=>service.submit(await create(),{requestId:key(),...changes},owner);
 const approved=async()=>{const wf=await start();await finish(wf.id);return wf;};
 const body=async(id,document,extra={})=>{const detail=await service.read(id,owner);return {requestId:key(),expectedVersion:detail.version,expectedDocumentHash:detail.editVersion,document,...extra};};
 const reject=(work,code)=>assert.rejects(work,error=>error.code===code);
 await test(label+' OPEN Group A persists directly and detects concurrent stale editing',async()=>{const id=await create(),current=await reqs.getRequisitionById(id),access=await reqs.requisitionAccess(current,owner,true,true);assert.equal((await reqs.updateRequisition(id,{handoverNotes:'Operational',expectedOperationVersion:access.operationVersion},owner)).success,true);assert.equal((await reqs.updateRequisition(id,{handoverNotes:'Stale',expectedOperationVersion:access.operationVersion},hr)).code,'REQUISITION_REVISION_STALE');assert.equal((await reqs.getRequisitionById(id)).headcount,2);});
 await test(label+' explicit first proposal stores pending document, main/list/report stay effective until last approval',async()=>{const id=await create(),original=await reqs.getRequisitionById(id),wf=await service.submit(id,{requestId:key(),expectedDocumentHash:reqs.approvalContentHash(original),document:{headcount:5,jobDescription:'Pending first JD'}},owner);let detail=await service.read(wf.id,owner);assert.equal(detail.submissions[0].document.headcount,5);assert.equal(detail.effectiveDocument.headcount,2);assert.equal((await reqs.getRequisitions({viewer:owner,approvalEnabled:true})).items.find(item=>item.id===id).headcount,2);await action(wf.id);assert.equal((await reqs.getRequisitionById(id)).headcount,2);const final=await action(wf.id);assert.equal(final.appliedRevision.revision,1);const applied=await service.read(wf.id,owner);assert.equal(applied.effectiveRevision.revision,1);assert.equal(applied.events.at(-1).appliedRevision.submissionId,applied.submissionId);assert.equal((await reqs.getRequisitionById(id)).headcount,5);assert.equal((await reqs.getRequisitionById(id)).jobDescription,'Pending first JD');assert.equal((await reqs.getRequisitionById(id)).status,'OPEN');});
 await test(label+' creator APPROVED resubmission starts at level one and preserves all old decisions',async()=>{const wf=await approved(),before=await service.read(wf.id,owner);await service.resubmit(wf.id,await body(wf.id,{headcount:6,jobDescription:'Approved revision'}),owner);const after=await service.read(wf.id,owner);assert.equal(after.submissions.length,2);assert.equal(after.submissions[1].revision,2);assert.deepEqual(after.submissions[0],before.submissions[0]);assert.deepEqual(after.events.slice(0,before.events.length),before.events);assert.deepEqual(after.steps.map(step=>step.status),['PENDING','WAITING']);assert.equal(after.effectiveDocument.headcount,2);await finish(wf.id);assert.equal((await reqs.getRequisitionById(wf.requisitionId)).headcount,6);});
 for(const role of ['HR_MANAGER','ADMIN'])await test(label+' '+role+' delegated submission requires reason and records original creator/actor/time',async()=>{const wf=await approved(),actor=users[role],data=await body(wf.id,{headcount:7});await reject(()=>service.resubmit(wf.id,data,actor),'APPROVAL_DELEGATION_REASON_REQUIRED');await service.resubmit(wf.id,{...data,reason:'Owner unavailable; audited submission'},actor);const detail=await service.read(wf.id,actor),audit=detail.submissions.at(-1).document.approvalRevision;assert.equal(detail.creatorId,owner.id);assert.equal(audit.creatorId,owner.id);assert.equal(audit.actorId,actor.id);assert.equal(audit.onBehalf,true);assert.ok(Number.isFinite(Date.parse(audit.submittedAt)));assert.equal(detail.events.at(-1).actor_id,actor.id);assert.equal(detail.events.at(-1).comment,'Owner unavailable; audited submission');assert.equal(detail.effectiveDocument.headcount,2);});
 await test(label+' initial delegated submission has mandatory reason and never changes creator',async()=>{const id=await create();await reject(()=>service.submit(id,{requestId:key()},admin),'APPROVAL_DELEGATION_REASON_REQUIRED');const wf=await service.submit(id,{requestId:key(),reason:'Initial delegated send'},admin),detail=await service.read(wf.id,admin);assert.equal(detail.creatorId,owner.id);assert.equal(detail.submissions[0].document.submissionAudit.actorId,admin.id);assert.equal(detail.events[0].comment,'Initial delegated send');});
 for(const state of ['NEEDS_INFO','REJECTED'])await test(label+' '+state+' correction preserves main and old snapshots, then restarts and applies only after final approval',async()=>{const wf=await approved();await service.resubmit(wf.id,await body(wf.id,{headcount:8}),owner);await action(wf.id,state==='NEEDS_INFO'?'REQUEST_INFO':'REJECT','Please revise');const before=await service.read(wf.id,owner);assert.equal(before.effectiveDocument.headcount,2);await service.resubmit(wf.id,await body(wf.id,{headcount:9}),owner);const after=await service.read(wf.id,owner);assert.deepEqual(after.submissions.slice(0,2),before.submissions);assert.deepEqual(after.events.slice(0,before.events.length),before.events);assert.equal(after.submissions.at(-1).revision,3);assert.deepEqual(after.steps.map(step=>step.status),['PENDING','WAITING']);assert.equal(after.effectiveDocument.headcount,2);await finish(wf.id);assert.equal((await reqs.getRequisitionById(wf.requisitionId)).headcount,9);});
 await test(label+' simultaneous creator and HR sends persist one new revision',async()=>{const wf=await approved(),data=await body(wf.id,{headcount:10}),results=await Promise.allSettled([service.resubmit(wf.id,data,owner),service.resubmit(wf.id,{...data,requestId:key(),reason:'Delegated concurrent send'},hr)]);assert.equal(results.filter(result=>result.status==='fulfilled').length,1);assert.equal(results.find(result=>result.status==='rejected').reason.code,'APPROVAL_STALE_STEP');assert.equal((await service.read(wf.id,owner)).submissions.length,2);});
 await test(label+' exact submission retry is idempotent; changed retry cannot create another revision',async()=>{const wf=await approved(),data=await body(wf.id,{headcount:4}),results=await Promise.all([service.resubmit(wf.id,data,owner),service.resubmit(wf.id,data,owner)]);assert.deepEqual(results[0],results[1]);await reject(()=>service.resubmit(wf.id,{...data,document:{headcount:12}},owner),'APPROVAL_RETRY_CONFLICT');assert.equal((await service.read(wf.id,owner)).submissions.length,2);});
 await test(label+' stale document token and workflow version reject competing edits',async()=>{const wf=await approved(),data=await body(wf.id,{headcount:4});await reject(()=>service.resubmit(wf.id,{...data,expectedDocumentHash:'stale'},owner),'REQUISITION_REVISION_STALE');await reject(()=>service.resubmit(wf.id,{...data,expectedVersion:data.expectedVersion-1},owner),'APPROVAL_STALE_STEP');assert.equal((await service.read(wf.id,owner)).submissions.length,1);});
 await test(label+' final apply preserves operational updates made while revision is pending',async()=>{const wf=await approved();await service.resubmit(wf.id,await body(wf.id,{headcount:4}),owner);await reqs.updateRequisition(wf.requisitionId,{handoverNotes:'Concurrent operational note'},owner);await finish(wf.id);const current=await reqs.getRequisitionById(wf.requisitionId);assert.equal(current.headcount,4);assert.equal(current.handoverNotes,'Concurrent operational note');assert.equal(current.recruiterId,'usr-recruiter');});
 await test(label+' final apply rollback restores main, current step, workflow and history after event failure',async()=>{const wf=await approved();await service.resubmit(wf.id,await body(wf.id,{headcount:4}),owner);await action(wf.id);const before=await service.read(wf.id,owner),prepare=db.prepare.bind(db);db.prepare=sql=>sql.startsWith('INSERT INTO requisition_approval_events')?{run:async()=>{throw Error('FINAL_EVENT_FAILURE');}}:prepare(sql);try{await assert.rejects(()=>action(wf.id),/FINAL_EVENT_FAILURE/);}finally{db.prepare=prepare;}assert.deepEqual(await service.read(wf.id,owner),before);});
 await test(label+' intermediate failed main update cannot commit an approval',async()=>{const wf=await approved();await service.resubmit(wf.id,await body(wf.id,{headcount:4}),owner);await action(wf.id);const before=await service.read(wf.id,owner),prepare=db.prepare.bind(db);db.prepare=sql=>sql.startsWith('UPDATE requisitions SET title=')?{run:async()=>{throw Error('MAIN_APPLY_FAILURE');}}:prepare(sql);try{await assert.rejects(()=>action(wf.id),/MAIN_APPLY_FAILURE/);}finally{db.prepare=prepare;}assert.deepEqual(await service.read(wf.id,owner),before);});
 await test(label+' simultaneous final approvals apply once and replay cannot process a later round',async()=>{const wf=await approved();await service.resubmit(wf.id,await body(wf.id,{headcount:4}),owner);await action(wf.id);const before=await service.read(wf.id,owner),data={requestId:key(),action:'APPROVE',expectedVersion:before.version,expectedStepId:before.steps[1].id},results=await Promise.allSettled([service.decide(wf.id,data,approver),service.decide(wf.id,{...data,requestId:key()},approver)]);assert.equal(results.filter(result=>result.status==='fulfilled').length,1);assert.equal((await reqs.getRequisitionById(wf.requisitionId)).headcount,4);await service.resubmit(wf.id,await body(wf.id,{headcount:5}),owner);const pending=await service.read(wf.id,owner);assert.deepEqual(await service.decide(wf.id,data,approver),results.find(result=>result.status==='fulfilled').value);assert.deepEqual(await service.read(wf.id,owner),pending);});
 for(const state of ['IN_PROGRESS','CLOSED'])await test(label+' '+state+' prevents new submission and final application even for ADMIN',async()=>{const wf=await approved(),data=await body(wf.id,{headcount:4});await db.prepare('UPDATE requisitions SET status=? WHERE id=?').run(state,wf.requisitionId);await reject(()=>service.resubmit(wf.id,{...data,reason:'Administrative send'},admin),'REQUISITION_EDIT_STATE_FORBIDDEN');await db.prepare("UPDATE requisitions SET status='OPEN' WHERE id=?").run(wf.requisitionId);await service.resubmit(wf.id,data,owner);await action(wf.id);await db.prepare('UPDATE requisitions SET status=? WHERE id=?').run(state,wf.requisitionId);const before=await service.read(wf.id,owner);await reject(()=>action(wf.id),'REQUISITION_EDIT_STATE_FORBIDDEN');assert.deepEqual(await service.read(wf.id,owner),before);});
 await test(label+' outside-scope read/edit context and non-owner send are denied',async()=>{const id=await create({departmentId:'dept-2'},admin);await reject(()=>service.context(id,owner),'REQUISITION_OUT_OF_SCOPE');await reject(()=>service.submit(id,{requestId:key()},owner),'REQUISITION_OUT_OF_SCOPE');const own=await approved();for(const user of [users.RECRUITER,users.INTERVIEWER,users.CANDIDATE])await reject(async()=>service.resubmit(own.id,await body(own.id,{headcount:4}),user),'APPROVAL_FORBIDDEN');});
 await test(label+' creator cannot approve even after permission grant and existing snapshot stays untouched',async()=>{const wf=await approved(),role=await db.prepare("SELECT id FROM roles WHERE code='APPROVER'").get();await db.prepare('INSERT INTO user_roles(user_id,role_id) VALUES (?,?)').run(owner.id,role.id);const config=await configs.get((await db.prepare("SELECT id FROM approval_configurations WHERE department_id='dept-3'").get()).id),next=await configs.newVersion(config.id,{expectedVersion:config.versions[0].version,levels:[{order:1,salaryLimit:60000000,approverUserId:owner.id}]},hr.id);await configs.publish(next.id,next.versions[0].id,hr.id);const before=await service.read(wf.id,owner);try{await reject(async()=>service.resubmit(wf.id,await body(wf.id,{headcount:4}),owner),'SELF_APPROVAL_FORBIDDEN');assert.deepEqual(await service.read(wf.id,owner),before);}finally{const current=await configs.get(config.id),fixed=await configs.newVersion(config.id,{expectedVersion:current.versions[0].version,levels:[{order:1,salaryLimit:20000000,approverUserId:hr.id},{order:2,salaryLimit:60000000,approverUserId:approver.id}]},hr.id);await configs.publish(fixed.id,fixed.versions[0].id,hr.id);await db.prepare('DELETE FROM user_roles WHERE user_id=? AND role_id=?').run(owner.id,role.id);}});
 await test(label+' duplicate approvers cannot be published or silently merged',async()=>{await reject(()=>configs.create({departmentId:'dept-5',levels:[{order:1,salaryLimit:20000000,approverUserId:hr.id},{order:2,salaryLimit:60000000,approverUserId:hr.id}]},hr.id),'REPEATED_APPROVER_FORBIDDEN');});
 await test(label+' current configuration snapshot resolves new salary without changing historical snapshot',async()=>{const wf=await approved(),before=await service.read(wf.id,owner);await service.resubmit(wf.id,await body(wf.id,{proposedSalaryMax:19000000}),owner);const after=await service.read(wf.id,owner);assert.equal(after.steps.length,1);assert.deepEqual(after.submissions[0],before.submissions[0]);await finish(wf.id);assert.equal((await reqs.getRequisitionById(wf.requisitionId)).proposedSalaryMax,19000000);});
 await test(label+' invalid document cannot persist revision or main changes',async()=>{const wf=await approved(),before=await service.read(wf.id,owner);await reject(async()=>service.resubmit(wf.id,await body(wf.id,{headcount:0}),owner),'INVALID_HEADCOUNT');await reject(async()=>service.resubmit(wf.id,await body(wf.id,{departmentName:'Unrecognized department'}),owner),'INVALID_DEPARTMENT');assert.deepEqual(await service.read(wf.id,owner),before);});
 await test(label+' effective base changed independently cannot be overwritten at final approval',async()=>{const wf=await approved();await service.resubmit(wf.id,await body(wf.id,{headcount:4}),owner);await action(wf.id);await db.prepare('UPDATE requisitions SET headcount=3 WHERE id=?').run(wf.requisitionId);const before=await service.read(wf.id,owner);await reject(()=>action(wf.id),'REQUISITION_REVISION_STALE');assert.deepEqual(await service.read(wf.id,owner),before);});
 await test(label+' changing department applies canonical manager and name only on final approval',async()=>{const wf=await approved();await service.resubmit(wf.id,await body(wf.id,{departmentId:'dept-4'}, {reason:'Transfer department'}),hr);assert.equal((await reqs.getRequisitionById(wf.requisitionId)).departmentId,'dept-3');await finish(wf.id);const current=await reqs.getRequisitionById(wf.requisitionId),dept=await db.prepare("SELECT name,manager_id FROM departments WHERE id='dept-4'").get();assert.equal(current.departmentId,'dept-4');assert.equal(current.departmentName,dept.name);assert.equal(current.hiringManagerId,dept.manager_id);const originalDept=await db.prepare("SELECT name FROM departments WHERE id='dept-3'").get();await service.resubmit(wf.id,await body(wf.id,{departmentName:originalDept.name},{reason:'Canonical department-name compatibility'}),hr);assert.equal((await reqs.getRequisitionById(wf.requisitionId)).departmentId,'dept-4');await finish(wf.id);assert.equal((await reqs.getRequisitionById(wf.requisitionId)).departmentId,'dept-3');});
 const otherTitle=await new(require('../src/services/competencyService'))(db).createJobTitle({code:'REA-OTHER-'+label.replace(/\W/g,''),name:'Other approved title',level:'Senior',minSalary:10000000,maxSalary:50000000});
 const catalogs=new(require('../src/services/recruitmentCatalogService'))(db),createdLocation=await catalogs.createItem({type:'WORK_LOCATION',code:'REA-LOCATION',name:'Reapproval location',displayOrder:1}),createdMode=await catalogs.createItem({type:'WORK_MODE',code:'REA-MODE',name:'Reapproval mode',displayOrder:1});assert.equal(createdLocation.success,true);assert.equal(createdMode.success,true);const location=createdLocation.data,mode=createdMode.data;
 const future=new Date(Date.parse(reqs.businessDate()+'T12:00:00Z')+86400000).toISOString().slice(0,10);
 for(const [field,value]of Object.entries({title:'Revised title',jobTitleId:otherTitle.data.id,headcount:4,recruitmentReason:'NEW_HEADCOUNT',proposedSalaryMin:16000000,proposedSalaryMax:35000000,salaryJustification:'Business justification',neededDate:future,jobDescription:'Revised detailed JD',candidateRequirements:'Revised candidate requirements',workLocationId:location.id,workModeId:mode.id}))await test(label+' Group B '+field+' stays ineffective until final approval',async()=>{const wf=await approved(),original=await reqs.getRequisitionById(wf.requisitionId);assert.equal((await reqs.updateRequisition(wf.requisitionId,{[field]:value},owner,{approvalEnabled:true})).code,'REQUISITION_REAPPROVAL_REQUIRED');await service.resubmit(wf.id,await body(wf.id,{[field]:value}),owner);assert.equal((await reqs.getRequisitionById(wf.requisitionId))[field],original[field]);await finish(wf.id);assert.equal((await reqs.getRequisitionById(wf.requisitionId))[field],value);});
 await test(label+' legacy authored OPEN can migrate into approved content without guessing its creator',async()=>{const legacy=await reqs.createRequisition({title:'Legacy authored request',departmentId:'dept-3',hiringManagerId:owner.id,headcount:2},owner);assert.equal(legacy.success,true);const original=await reqs.getRequisitionById(legacy.data.id);assert.equal(original.createdBy,owner.id);const {formVersion,recruiterId,...document}=valid;const wf=await service.submit(original.id,{requestId:key(),expectedDocumentHash:reqs.approvalContentHash(original),document},owner);assert.equal((await reqs.getRequisitionById(original.id)).formVersion,undefined);await finish(wf.id);assert.equal((await reqs.getRequisitionById(original.id)).formVersion,'S2-10');assert.equal((await reqs.getRequisitionById(original.id)).createdBy,owner.id);});
 await test(label+' PENDING revision and missing APPROVED expectation cannot create another round',async()=>{const wf=await approved();const data=await body(wf.id,{headcount:4});await reject(()=>service.resubmit(wf.id,{...data,expectedDocumentHash:undefined},owner),'APPROVAL_EXPECTATION_REQUIRED');await service.resubmit(wf.id,data,owner);await reject(async()=>service.resubmit(wf.id,await body(wf.id,{headcount:5}),owner),'APPROVAL_STALE_STEP');assert.equal((await service.read(wf.id,owner)).submissions.length,2);});
 await test(label+' forged review/audit/ownership fields cannot enter an immutable revision',async()=>{const wf=await approved();for(const document of [{approvalRevision:{applyToMain:true}},{createdBy:admin.id},{status:'APPROVED'},{recruiterId:admin.id}])await assert.rejects(async()=>service.resubmit(wf.id,await body(wf.id,document),owner),error=>error.code==='INVALID_APPROVAL_DOCUMENT_FIELD');assert.equal((await service.read(wf.id,owner)).submissions.length,1);});
 await test(label+' pending content is excluded from dashboard and reporting totals',async()=>{const wf=await approved(),before=await reqs.getReports({viewer:owner,approvalEnabled:true});await service.resubmit(wf.id,await body(wf.id,{headcount:14}),owner);const pending=await reqs.getReports({viewer:owner,approvalEnabled:true});assert.equal(pending.report.summary.requisitions.totalHeadcount,before.report.summary.requisitions.totalHeadcount);await finish(wf.id);const after=await reqs.getReports({viewer:owner,approvalEnabled:true});assert.equal(after.report.summary.requisitions.totalHeadcount,before.report.summary.requisitions.totalHeadcount+12);});
 await test(label+' department manager and assigned recruiter can view workflow but cannot submit on behalf',async()=>{const id=await create({},admin),wf=await service.submit(id,{requestId:key()},admin);for(const user of [owner,users.RECRUITER]){const detail=await service.read(wf.id,user);assert.equal(detail.creatorId,admin.id);assert.equal(detail.canResubmit,false);assert.ok((await service.list(user)).some(item=>item.id===wf.id));}await finish(wf.id);await reject(async()=>service.resubmit(wf.id,await body(wf.id,{headcount:4},{reason:'Attempted unauthorized delegation'}),owner),'APPROVAL_OWNER_REQUIRED');});
 await test(label+' cached HR role cannot expose a foreign workflow to Hiring Manager',async()=>{const id=await create({departmentId:'dept-2'},admin),wf=await service.submit(id,{requestId:key()},admin);await reject(()=>service.read(wf.id,{...owner,roles:['HR_MANAGER']}),'APPROVAL_FORBIDDEN');assert.equal((await service.list({...owner,roles:['HR_MANAGER']})).some(item=>item.id===wf.id),false);});
 return {service,reqs,users,owner,hr,approver,create,approved,body,finish,action,valid};
}
async function main(){
 const app=await openApplication();try{
  const state=await cases(app.db,'SQLite'),config=require('../src/config/config');config.REQUISITION_APPROVAL_ENABLED=true;
  const sessions={};for(const [role,email]of Object.entries({HIRING_MGR:'hiringmgr@company.com',HR_MANAGER:'hrmanager@company.com',ADMIN:'admin@company.com',APPROVER:'approver@company.com',RECRUITER:'recruiter@company.com',CANDIDATE:'candidate@example.com'}))sessions[role]=await app.login(email);
  await test('HTTP unauthenticated and wrong-role context remain protected',async()=>{const id=await state.create();assert.equal((await app.api('GET','/requisition-approvals/context/'+id)).status,401);assert.equal((await app.api('GET','/requisition-approvals/context/'+id,sessions.CANDIDATE.token)).status,403);assert.equal((await app.api('GET','/requisition-approvals/context/'+id,sessions.HIRING_MGR.token)).status,200);});
  await test('flag OFF rejects review submission and never bypasses Group B approval',async()=>{const id=await state.create(),before=await state.reqs.getRequisitionById(id);config.REQUISITION_APPROVAL_ENABLED=false;try{assert.equal((await app.api('POST','/requisition-approvals',sessions.HIRING_MGR.token,{requisitionId:id,requestId:key(),document:{headcount:5},expectedDocumentHash:state.reqs.approvalContentHash(before)})).status,404);const update=await app.api('PUT','/requisitions/'+id,sessions.HIRING_MGR.token,{headcount:5});assert.equal(update.status,409);assert.equal(update.data.code,'REQUISITION_REAPPROVAL_REQUIRED');assert.equal(update.data.approvalEnabled,false);assert.deepEqual(await state.reqs.getRequisitionById(id),before);assert.equal((await app.api('PUT','/requisitions/'+id,sessions.HIRING_MGR.token,{handoverNotes:'Flag-off note'})).status,200);}finally{config.REQUISITION_APPROVAL_ENABLED=true;}});
  await test('HTTP delegated send rejects missing reason and audits ADMIN actor without creator replacement',async()=>{const wf=await state.approved(),data=await state.body(wf.id,{headcount:5}),route='/requisition-approvals/'+wf.id+'/resubmit';assert.equal((await app.api('POST',route,sessions.ADMIN.token,data)).status,400);assert.equal((await app.api('POST',route,sessions.ADMIN.token,{...data,reason:'HTTP admin delegate'})).status,200);const read=await app.api('GET','/requisition-approvals/'+wf.id,sessions.ADMIN.token);assert.equal(read.data.data.events.at(-1).actor_id,state.users.ADMIN.id);assert.equal(read.data.data.creatorId,state.owner.id);assert.equal(JSON.stringify(read.data).includes('minSalary'),false);});
  const {createFrontendRuntime}=require('./helpers/frontendRuntime'),runtime=await createFrontendRuntime(app.base,'/login');let uiWorkflow;
  await test('frontend effective/pending separation and explicit send from OPEN editor',async()=>{runtime.nodes.get('email').value='hiringmgr@company.com';runtime.nodes.get('password').value='Ats@123456';await runtime.nodes.get('login-form').dispatch('submit');await runtime.settle();uiWorkflow=await state.approved();await vm.runInContext('openRequisitionDetails('+JSON.stringify(uiWorkflow.requisitionId)+',true)',runtime.context);runtime.nodes.get('create-req-headcount-input').value='5';await runtime.nodes.get('create-req-form').dispatch('submit');await runtime.settle();assert.equal(runtime.nodes.get('create-req-reapprove').classList.contains('hidden'),false);assert.equal((await state.reqs.getRequisitionById(uiWorkflow.requisitionId)).headcount,2);await runtime.nodes.get('create-req-reapprove').dispatch('click');await runtime.settle();assert.equal(runtime.nodes.get('s302-revision-form').classList.contains('hidden'),false);assert.match(runtime.nodes.get('s302-diff').textContent,/headcount: 2 → 5/);runtime.requests.length=0;await Promise.all([runtime.nodes.get('s302-revision-form').dispatch('submit'),runtime.nodes.get('s302-revision-form').dispatch('submit')]);await runtime.settle();assert.equal(runtime.requests.filter(item=>item.path.endsWith('/resubmit')).length,1);assert.match(runtime.nodes.get('s302-effective').textContent,/Số lượng: 2/);assert.equal((await state.reqs.getRequisitionById(uiWorkflow.requisitionId)).headcount,2);assert.equal((await state.service.read(uiWorkflow.id,state.owner)).submissions.at(-1).document.headcount,5);});
  await test('frontend reviewer sees pending diff and final approval applies it',async()=>{await state.action(uiWorkflow.id);await runtime.nodes.get('logout-btn').dispatch('click');runtime.nodes.get('email').value='approver@company.com';runtime.nodes.get('password').value='Ats@123456';await runtime.nodes.get('login-form').dispatch('submit');await runtime.settle();await runtime.window.ATS_REQUISITION_APPROVAL_UI.open(uiWorkflow.id);assert.equal(runtime.nodes.get('s302-actions').classList.contains('hidden'),false);assert.match(runtime.nodes.get('s302-diff').textContent,/headcount: 2 → 5/);await runtime.nodes.get('s302-approve').dispatch('click');await runtime.settle();assert.equal((await state.reqs.getRequisitionById(uiWorkflow.requisitionId)).headcount,5);assert.match(runtime.nodes.get('s302-status').textContent,/Đã duyệt/);});
  await test('frontend HR delegated resubmit validates reason before request and displays audit history',async()=>{await runtime.nodes.get('logout-btn').dispatch('click');runtime.nodes.get('email').value='hrmanager@company.com';runtime.nodes.get('password').value='Ats@123456';await runtime.nodes.get('login-form').dispatch('submit');await runtime.settle();await runtime.window.ATS_REQUISITION_APPROVAL_UI.open(uiWorkflow.id);assert.equal(runtime.nodes.get('s302-revision-form').classList.contains('hidden'),false);runtime.nodes.get('s302-quantity').value='6';runtime.nodes.get('s302-delegation-reason').value='';runtime.requests.length=0;await runtime.nodes.get('s302-revision-form').dispatch('submit');assert.equal(runtime.requests.filter(item=>item.path.endsWith('/resubmit')).length,0);assert.match(runtime.nodes.get('s302-message').textContent,/lý do gửi thay/);runtime.nodes.get('s302-delegation-reason').value='HR sends for owner';await runtime.nodes.get('s302-revision-form').dispatch('submit');await runtime.settle();assert.match(runtime.nodes.get('s302-history').textContent,/HR sends for owner/);assert.equal((await state.reqs.getRequisitionById(uiWorkflow.requisitionId)).headcount,5);assert.equal((await state.service.read(uiWorkflow.id,state.hr)).submissions.at(-1).document.headcount,6);});
  await test('frontend initial pending proposal can be submitted without preexisting workflow',async()=>{await runtime.nodes.get('logout-btn').dispatch('click');runtime.nodes.get('email').value='hiringmgr@company.com';runtime.nodes.get('password').value='Ats@123456';await runtime.nodes.get('login-form').dispatch('submit');await runtime.settle();const id=await state.create(),original=await state.reqs.getRequisitionById(id);await runtime.window.ATS_REQUISITION_APPROVAL_UI.propose(id,{headcount:8},state.reqs.approvalContentHash(original));await runtime.nodes.get('s302-revision-form').dispatch('submit');await runtime.settle();const workflow=await app.db.prepare('SELECT id FROM requisition_approval_workflows WHERE requisition_id=?').get(id);assert.ok(workflow);assert.equal((await state.service.read(workflow.id,state.owner)).submissions[0].document.headcount,8);assert.equal((await state.reqs.getRequisitionById(id)).headcount,2);});
  await test('legacy frontend department-name edit resolves canonical ID and preserves main until final approval',async()=>{await runtime.nodes.get('logout-btn').dispatch('click');runtime.nodes.get('email').value='hrmanager@company.com';runtime.nodes.get('password').value='Ats@123456';await runtime.nodes.get('login-form').dispatch('submit');await runtime.settle();const result=await state.reqs.createRequisition({title:'Legacy UI request',departmentId:'dept-3',hiringManagerId:state.owner.id,headcount:2},state.owner),id=result.data.id,dept=await app.db.prepare("SELECT name FROM departments WHERE id='dept-4'").get();await vm.runInContext('openRequisitionDetails('+JSON.stringify(id)+',true)',runtime.context);runtime.nodes.get('req-detail-dept-input').value=dept.name;await runtime.nodes.get('req-detail-form').dispatch('submit');await runtime.settle();assert.equal(runtime.nodes.get('req-detail-reapprove').classList.contains('hidden'),false);await runtime.nodes.get('req-detail-reapprove').dispatch('click');await runtime.settle();assert.equal(runtime.nodes.get('s302-department').value,'dept-4');for(const [field,value]of Object.entries({'s302-job':state.valid.jobTitleId,'s302-quantity':'2','s302-reason':'REPLACEMENT','s302-min':'15000000','s302-max':'30000000','s302-needed':state.valid.neededDate,'s302-description':'Legacy revised JD','s302-requirements':'Legacy revised requirements','s302-delegation-reason':'HR legacy department correction'}))runtime.nodes.get(field).value=value;await runtime.nodes.get('s302-revision-form').dispatch('submit');await runtime.settle();const wf=await app.db.prepare('SELECT id FROM requisition_approval_workflows WHERE requisition_id=?').get(id);assert.ok(wf,runtime.nodes.get('s302-message').textContent);assert.equal((await state.reqs.getRequisitionById(id)).departmentId,'dept-3');assert.equal((await state.service.read(wf.id,state.hr)).submissions[0].document.departmentId,'dept-4');await state.finish(wf.id);assert.equal((await state.reqs.getRequisitionById(id)).departmentId,'dept-4');});
  await test('late real PUT response cannot attach the previous proposal to a different open editor',async()=>{for(const legacy of [false,true]){const make=async()=>legacy?(await state.reqs.createRequisition({title:'Latency fixture',departmentId:'dept-3',hiringManagerId:state.owner.id,headcount:2},state.owner)).data.id:await state.create();const first=await make(),second=await make();await vm.runInContext('openRequisitionDetails('+JSON.stringify(first)+',true)',runtime.context);runtime.nodes.get(legacy?'req-detail-title-input':'create-req-headcount-input').value=legacy?'First pending title':'4';const transport=runtime.context.fetch;let release,arrived;const ready=new Promise(resolve=>arrived=resolve),hold=new Promise(resolve=>release=resolve);runtime.context.fetch=async(url,options)=>{const response=await transport(url,options);if(options?.method==='PUT'&&String(url).includes('/requisitions/'+first)){arrived();await hold;}return response;};try{const pending=runtime.nodes.get(legacy?'req-detail-form':'create-req-form').dispatch('submit');await ready;await vm.runInContext('openRequisitionDetails('+JSON.stringify(second)+',true)',runtime.context);release();await pending;assert.equal(runtime.nodes.get(legacy?'req-detail-reapprove':'create-req-reapprove').classList.contains('hidden'),true);assert.equal((await state.reqs.getRequisitionById(first)).headcount,2);assert.equal((await state.reqs.getRequisitionById(second)).headcount,2);}finally{release();runtime.context.fetch=transport;}}});
  await test('frontend history, session and lifecycle remain safe with one listener',async()=>{runtime.window.ATS_ROUTER.navigate('/dashboard');await runtime.settle();assert.equal(runtime.nodes.get('s302-modal').classList.contains('hidden'),true);assert.equal(runtime.nodes.get('s302-effective').textContent,'');assert.equal(runtime.nodes.get('s302-revision-form').listeners.get('submit').length,1);assert.deepEqual(runtime.errors,[]);});
 }finally{await app.close();}
 const {PGlite}=require('@electric-sql/pglite'),{PostgresDatabase}=require('../src/db/postgres'),engine=new PGlite();let tail=Promise.resolve();
 const query=async(sql,params)=>{const result=params===undefined?(await engine.exec(sql)).at(-1):await engine.query(sql,params);return{rows:(result?.rows||[]).map(row=>Object.fromEntries(Object.entries(row).map(([key,value])=>[key,value instanceof Date?(result.fields.find(field=>field.name===key)?.dataTypeID===1082?value.toISOString().slice(0,10):value.toISOString()):typeof value==='bigint'?Number(value):typeof value==='string'&&[20,1700].includes(result.fields.find(field=>field.name===key)?.dataTypeID)?require('../src/db/postgres').pgTypes().getTypeParser(result.fields.find(field=>field.name===key).dataTypeID)(value):value]))),rowCount:result?.affectedRows||result?.rows?.length||0};};
 const pg=new PostgresDatabase({},{on(){},query,async connect(){const previous=tail;let release;tail=new Promise(resolve=>release=resolve);await previous;return{query,release};},async end(){await engine.close();}});
 try{await require('../src/db/migrate-postgres').migrate(pg);await pg.transaction(()=>require('../src/db/seed').seedDatabase(pg));await cases(pg,'PostgreSQL embedded');}finally{await pg.close();}
 console.log('REAPPROVAL_RESULT '+JSON.stringify({passed,failed,total:passed+failed}));process.exitCode=failed?1:0;
}
main().catch(error=>{console.error(error.stack);process.exitCode=1;});
