const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),vm=require('node:vm');
const root=path.resolve(__dirname,'../..');for(const file of ['.git','.env','backend/data/ats.db','backend/data/ats.db-shm','backend/data/ats.db-wal','backend/data/ats_test.db'])assert.equal(fs.existsSync(path.join(root,file)),false,'Fresh isolated copy required');
for(const key of Object.keys(process.env))if(/^(DATABASE_|DB_|PG|ATS_POSTGRES_|SMTP_|EMAIL_|MAIL_|HEADCOUNT_|APPROVAL_|REQUISITION_APPROVAL_)/.test(key))delete process.env[key];Object.assign(process.env,{NODE_ENV:'test',DB_PROVIDER:'sqlite',EMAIL_MODE:'simulated'});
const {openApplication}=require('./helpers/coverageApplication'),Requisitions=require('../src/services/requisitionService'),Approvals=require('../src/services/requisitionApprovalService'),Configurations=require('../src/services/approvalConfigurationService').ApprovalConfigurationService,{HeadcountBudgetService:Budgets}=require('../src/services/headcountBudgetService');
const mode=process.argv[2],key=()=>crypto.randomUUID();let passed=0,failed=0;
async function test(name,action){try{await action();passed++;console.log('[PASS] '+name);}catch(error){failed++;console.error('[FAIL] '+name+'\n'+error.stack);}}
const reject=(action,code)=>assert.rejects(action,error=>error.code===code);
async function setup(db,label){await require('../src/db/migrate-approval-configurations').migrate(db);await require('../src/db/migrate-requisition-approvals').migrate(db);if(mode==='s3-04')await require('../src/db/migrate-headcount-budgets').migrate(db);const reqs=new Requisitions(db),approvals=new Approvals(db),configs=new Configurations(db),budgets=new Budgets(db),auth=new(require('../src/services/authService'))(db),users={};for(const [role,email]of Object.entries({ADMIN:'admin@company.com',HR_MANAGER:'hrmanager@company.com',HIRING_MGR:'hiringmgr@company.com',APPROVER:'approver@company.com',RECRUITER:'recruiter@company.com',INTERVIEWER:'interviewer@company.com',CANDIDATE:'candidate@example.com'}))users[role]=(await auth.login(email,'Ats@123456')).data.user;
 const owner=users.HIRING_MGR,hr=users.HR_MANAGER,admin=users.ADMIN,reviewer=users.APPROVER;const title=await new(require('../src/services/competencyService'))(db).createJobTitle({code:mode+'-'+label.replace(/\W/g,''),name:'Sprint 3 test position',level:'Senior',minSalary:100,maxSalary:1000});assert.equal(title.success,true);
 for(const departmentId of ['dept-3','dept-2','dept-4']){const c=await configs.create({departmentId,levels:[{order:1,salaryLimit:200,approverUserId:hr.id},{order:2,salaryLimit:1000,approverUserId:reviewer.id}]},hr.id);await configs.publish(c.id,c.versions[0].id,hr.id);}
 let nextYear=Number(reqs.businessDate().slice(0,4))+1;const valid={formVersion:'S2-10',departmentId:'dept-3',jobTitleId:title.data.id,headcount:2,recruitmentReason:'NEW_HEADCOUNT',proposedSalaryMin:150,proposedSalaryMax:300,neededDate:nextYear+'-06-15',jobDescription:'Effective document',candidateRequirements:'Required skills'};
 const create=async(data={},actor=owner)=>{const result=await reqs.createRequisition({...valid,...data},actor);assert.equal(result.success,true);return result.data.id;};
 const start=async data=>approvals.submit(await create(data),{requestId:key()},owner);
 const decide=async(id,action='APPROVE',comment='')=>{const detail=await approvals.read(id,owner),step=detail.steps.find(item=>item.status==='PENDING'),actor=Object.values(users).find(user=>user.id===step.approver_id);return approvals.decide(id,{requestId:key(),expectedVersion:detail.version,expectedStepId:step.id,action,comment},actor);};
 const finish=async id=>{while((await approvals.read(id,owner)).status==='PENDING')await decide(id);};
 const resubmit=async(id,document,actor=owner)=>{const detail=await approvals.read(id,actor);return approvals.resubmit(id,{requestId:key(),expectedVersion:detail.version,expectedDocumentHash:detail.editVersion,document,...(actor.id!==detail.creatorId?{reason:'Delegated finance revision'}:{})},actor);};
 const quota=async(headcount=10,salary=1000000,departmentId='dept-3',year=nextYear++)=>{await budgets.save({departmentId,year,approvedHeadcount:headcount,annualSalaryBudget:salary},hr);return year;};
 return{db,users,owner,hr,admin,reviewer,reqs,approvals,budgets,configs,valid,create,start,decide,finish,resubmit,quota};
}
async function trackingCases(s,label){const {db,approvals,reqs,owner,hr,admin,reviewer,create,start,decide,resubmit,finish}=s;
 await test(label+' empty tracking returns NOT_SUBMITTED without inventing levels',async()=>{const id=await create(),data=await approvals.tracking(id,owner);assert.equal(data.status,'NOT_SUBMITTED');assert.equal(data.waitingFor,null);assert.deepEqual(data.rounds,[]);});
 const wf=await start();
 await test(label+' tracking shows full resolved chain in stable order and waiting person',async()=>{const data=await approvals.tracking(wf.requisitionId,owner);assert.deepEqual(data.rounds[0].steps.map(step=>step.order),[1,2]);assert.deepEqual(data.rounds[0].steps.map(step=>step.status),['PENDING','WAITING']);assert.equal(data.waitingFor.id,hr.id);assert.equal(data.rounds[0].isCurrent,true);assert.ok(data.rounds[0].configurationVersionId);});
 await test(label+' actual decision actor/time/comment comes from immutable event',async()=>{await decide(wf.id,'APPROVE','First level accepted');const data=await approvals.tracking(wf.requisitionId,owner),step=data.rounds[0].steps[0];assert.equal(step.status,'APPROVED');assert.equal(step.assignedApprover.id,hr.id);assert.equal(step.decisions[0].actor.id,hr.id);assert.equal(step.decisions[0].comment,'First level accepted');assert.ok(Number.isFinite(Date.parse(step.decisions[0].at)));assert.equal(data.waitingFor.id,reviewer.id);});
 await test(label+' NEEDS_INFO then fresh revision retains prior steps and no prior decision reuse',async()=>{await decide(wf.id,'REQUEST_INFO','Provide missing details');const before=await approvals.tracking(wf.requisitionId,owner);assert.equal(before.status,'NEEDS_INFO');assert.equal(before.waitingFor,null);await resubmit(wf.id,{jobDescription:'Revised document'});const data=await approvals.tracking(wf.requisitionId,owner);assert.equal(data.rounds.length,2);assert.deepEqual(data.rounds[0].steps,before.rounds[0].steps);assert.equal(data.rounds[0].isCurrent,false);assert.equal(data.rounds[1].isCurrent,true);assert.equal(data.rounds[1].steps[0].decisions.length,0);assert.equal(data.waitingFor.id,hr.id);});
 await test(label+' rejection and APPROVED reapproval preserve all prior rounds',async()=>{await decide(wf.id,'REJECT','Not acceptable');const old=await approvals.tracking(wf.requisitionId,owner);await resubmit(wf.id,{jobDescription:'Corrected document'});await finish(wf.id);await resubmit(wf.id,{headcount:3});const data=await approvals.tracking(wf.requisitionId,owner);assert.equal(data.rounds.length,4);assert.deepEqual(data.rounds.slice(0,2).map(round=>round.steps),old.rounds.map(round=>round.steps));assert.equal(data.effectiveRevision,3);assert.equal(data.currentRevision,4);});
 for(const user of [admin,hr,owner,reviewer])await test(label+' authorized tracking '+user.roles.join('+'),async()=>assert.equal((await approvals.tracking(wf.requisitionId,user)).workflowId,wf.id));
 await test(label+' foreign ID, nonexistent ID, cached roles and candidate cannot expose history',async()=>{const id=await create({departmentId:'dept-2'},admin);await reject(()=>approvals.tracking(id,owner),'REQUISITION_OUT_OF_SCOPE');await reject(()=>approvals.tracking(id,{...owner,roles:['ADMIN']}),'REQUISITION_OUT_OF_SCOPE');await reject(()=>approvals.tracking('missing-id',owner),'REQUISITION_NOT_FOUND');await reject(()=>approvals.tracking(wf.requisitionId,s.users.CANDIDATE),'APPROVAL_FORBIDDEN');});
 await test(label+' query count does not grow with number of revisions/steps',async()=>{const prepare=db.prepare.bind(db);let count=0;db.prepare=sql=>{count++;return prepare(sql);};let initial;try{await approvals.tracking(wf.requisitionId,owner);initial=count;}finally{db.prepare=prepare;}await finish(wf.id);for(let i=0;i<3;i++){await resubmit(wf.id,{headcount:4+i});await finish(wf.id);}count=0;db.prepare=sql=>{count++;return prepare(sql);};try{await approvals.tracking(wf.requisitionId,owner);assert.equal(count,initial);}finally{db.prepare=prepare;}});
 await test(label+' snapshot configuration change cannot alter historical chain',async()=>{const data=await approvals.tracking(wf.requisitionId,owner),config=await s.configs.get((await db.prepare("SELECT id FROM approval_configurations WHERE department_id='dept-3'").get()).id),next=await s.configs.newVersion(config.id,{expectedVersion:config.versions[0].version,levels:[{order:1,salaryLimit:1000,approverUserId:reviewer.id}]},hr.id);await s.configs.publish(next.id,next.versions[0].id,hr.id);assert.deepEqual((await approvals.tracking(wf.requisitionId,owner)).rounds,data.rounds);});
 await test(label+' immutable history and snapshot reject direct update/delete',async()=>{for(const sql of ['UPDATE requisition_approval_events SET comment=\'Changed\' WHERE workflow_id=?','DELETE FROM requisition_approval_events WHERE workflow_id=?','UPDATE requisition_approval_submissions SET document_json=\'{}\' WHERE workflow_id=?','DELETE FROM requisition_approval_submissions WHERE workflow_id=?'])await assert.rejects(async()=>db.prepare(sql).run(wf.id),/IMMUTABLE/);});
 const current=await s.configs.get((await db.prepare("SELECT id FROM approval_configurations WHERE department_id='dept-3'").get()).id),restored=await s.configs.newVersion(current.id,{expectedVersion:current.versions[0].version,levels:[{order:1,salaryLimit:200,approverUserId:hr.id},{order:2,salaryLimit:1000,approverUserId:reviewer.id}]},hr.id);await s.configs.publish(restored.id,restored.versions[0].id,hr.id);
 return wf;
}
async function budgetCases(s,label){const {db,budgets,owner,hr,admin,reqs,approvals,create,start,decide,finish,resubmit,quota}=s,config=require('../src/config/config');config.HEADCOUNT_BUDGET_ENABLED=true;
 await test(label+' migration is additive/idempotent and permission sync preserves unrelated grants',async()=>{const before=await db.prepare('SELECT * FROM role_permissions ORDER BY role_id,permission_id').all();await require('../src/db/migrate-headcount-budgets').migrate(db);await require('../src/db/migrate-headcount-budgets').verify(db);assert.deepEqual(await db.prepare('SELECT * FROM role_permissions ORDER BY role_id,permission_id').all(),before);});
 await test(label+' additive deployment repairs only canonical requisite edit grants without privilege escalation',async()=>{await db.prepare("DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE code IN ('requisition.edit','requisition.draft.edit'))").run();await require('../src/db/migrate-headcount-budgets').migrate(db);const rbac=new(require('../src/middlewares/rbacMiddleware'))(db);for(const role of ['HR_MANAGER','HIRING_MGR','RECRUITER'])assert.equal(await rbac.hasPermission(s.users[role].id,'requisition.edit'),true);for(const role of ['APPROVER','INTERVIEWER','CANDIDATE'])assert.equal(await rbac.hasPermission(s.users[role].id,'requisition.edit'),false);assert.equal(await rbac.hasPermission(owner.id,'requisition.draft.edit'),true);});
 await test(label+' annual salary uses remaining months including needed month',async()=>{for(const [month,months]of [['01',12],['06',7],['12',1]]){const doc=budgets.document({...s.valid,neededDate:'2030-'+month+'-15'});assert.equal(doc.months,months);assert.equal(doc.annualCost,2*300*months);}await reject(async()=>budgets.document({...s.valid,neededDate:'2030-02-30'}),'BUDGET_DOCUMENT_INCOMPLETE');});
 await test(label+' budget creates unique department/year and appends versions without overwriting history',async()=>{const year=await quota();await reject(()=>budgets.save({departmentId:'dept-3',year,approvedHeadcount:10,annualSalaryBudget:1000000},hr),'BUDGET_VERSION_CONFLICT');const result=await budgets.save({departmentId:'dept-3',year,approvedHeadcount:12,annualSalaryBudget:2000000,expectedVersion:1,reason:'New annual plan'},admin);assert.equal(result.version,2);const history=await budgets.history('dept-3',year,owner);assert.deepEqual(history.versions.map(row=>row.approvedHeadcount),[10,12]);for(const table of ['headcount_budget_versions'])for(const operation of ['UPDATE','DELETE'])await assert.rejects(async()=>db.prepare(operation==='UPDATE'?'UPDATE '+table+' SET reason=\'changed\'':'DELETE FROM '+table).run(),/IMMUTABLE/);});
 await test(label+' Draft does not consume; OPEN counts new and replacement hiring equally',async()=>{const year=await quota();await create({status:'DRAFT',neededDate:year+'-06-15',headcount:5});await create({neededDate:year+'-06-15',recruitmentReason:'NEW_HEADCOUNT'});await create({neededDate:year+'-06-15',recruitmentReason:'REPLACEMENT'});const data=await budgets.availability({departmentId:'dept-3',year},owner);assert.equal(data.usedHeadcount,4);assert.equal(data.remainingHeadcount,6);assert.equal(data.usedSalary,8400);});
 await test(label+' exact quota accepts and excess rollback leaves no requisition',async()=>{const year=await quota(2,4200);await create({neededDate:year+'-06-15'});const before=(await db.prepare('SELECT COUNT(*) AS n FROM requisitions').get()).n;await reject(()=>reqs.createRequisition({...s.valid,neededDate:year+'-06-15',headcount:1},owner),'HEADCOUNT_BUDGET_EXCEEDED');assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM requisitions').get()).n,before);});
 await test(label+' salary cap independently blocks even if headcount remains',async()=>{const year=await quota(10,1000);await reject(()=>reqs.createRequisition({...s.valid,neededDate:year+'-06-15'},owner),'HEADCOUNT_BUDGET_EXCEEDED');});
 await test(label+' missing budget blocks OPEN but not DRAFT; no guessed year/cost',async()=>{const year=2090;await reject(()=>reqs.createRequisition({...s.valid,neededDate:year+'-06-15'},owner),'HEADCOUNT_BUDGET_UNAVAILABLE');assert.ok(await create({status:'DRAFT',neededDate:year+'-06-15'}));await reject(()=>reqs.createRequisition({title:'Legacy missing finance',departmentId:'dept-3',hiringManagerId:owner.id},owner),'BUDGET_DOCUMENT_INCOMPLETE');});
 for(const actor of [hr,admin])await test(label+' '+actor.roles.join('+')+' confirms bound exception with immutable audit',async()=>{const year=await quota(1,1000),id=await create({status:'DRAFT',neededDate:year+'-06-15'});await reject(()=>reqs.updateRequisition(id,{status:'OPEN'},owner),'HEADCOUNT_BUDGET_EXCEEDED');await reject(()=>budgets.confirm({requisitionId:id,expectedVersion:1,reason:' '},actor),'BUDGET_EXCEPTION_REASON_REQUIRED');const result=await budgets.confirm({requisitionId:id,expectedVersion:1,reason:'Approved annual exception'},actor);assert.equal(result.headcountOver,1);assert.equal(result.salaryOver,3200);assert.equal((await reqs.updateRequisition(id,{status:'OPEN'},owner)).success,true);const history=await budgets.history('dept-3',year,hr);assert.equal(history.exceptions[0].confirmedBy,actor.id);assert.equal(history.exceptions[0].reason,'Approved annual exception');assert.equal(history.exceptions[0].approvedHeadcount,1);assert.ok(Number.isFinite(Date.parse(history.exceptions[0].createdAt)));for(const sql of ['UPDATE headcount_budget_exceptions SET reason=\'Changed\' WHERE id=?','DELETE FROM headcount_budget_exceptions WHERE id=?'])await assert.rejects(async()=>db.prepare(sql).run(result.id),/IMMUTABLE/);});
 await test(label+' Hiring cannot self override even with forged role or manual grant',async()=>{const year=await quota(1),id=await create({status:'DRAFT',neededDate:year+'-06-15'}),role=await db.prepare("SELECT id FROM roles WHERE code='HIRING_MGR'").get();await db.prepare("INSERT INTO role_permissions(role_id,permission_id) SELECT ?,id FROM permissions WHERE code='headcount_budget.override'").run(role.id);try{await reject(()=>budgets.confirm({requisitionId:id,expectedVersion:1,reason:'Attempted'}, {...owner,roles:['ADMIN']}),'BUDGET_FORBIDDEN');}finally{await db.prepare("DELETE FROM role_permissions WHERE role_id=? AND permission_id IN (SELECT id FROM permissions WHERE code='headcount_budget.override')").run(role.id);}});
 await test(label+' financial changes and budget version invalidate stale exception',async()=>{const year=await quota(1),id=await create({status:'DRAFT',neededDate:year+'-06-15'});await budgets.confirm({requisitionId:id,expectedVersion:1,reason:'Original amount'},hr);await reject(()=>reqs.updateRequisition(id,{status:'OPEN',headcount:3},owner),'HEADCOUNT_BUDGET_EXCEEDED');await budgets.save({departmentId:'dept-3',year,approvedHeadcount:1,annualSalaryBudget:2000000,expectedVersion:1},hr);await reject(()=>reqs.updateRequisition(id,{status:'OPEN'},owner),'HEADCOUNT_BUDGET_EXCEEDED');await reject(()=>budgets.confirm({requisitionId:id,expectedVersion:1,reason:'Stale budget'},hr),'BUDGET_VERSION_CONFLICT');});
 await test(label+' concurrent OPEN creators cannot both consume the same remaining quota',async()=>{const year=await quota(2);const results=await Promise.allSettled([reqs.createRequisition({...s.valid,neededDate:year+'-06-15'},owner),reqs.createRequisition({...s.valid,neededDate:year+'-06-15'},hr)]);assert.equal(results.filter(row=>row.status==='fulfilled').length,1);assert.equal(results.find(row=>row.status==='rejected').reason.code,'HEADCOUNT_BUDGET_EXCEEDED');assert.equal((await budgets.availability({departmentId:'dept-3',year},hr)).remainingHeadcount,0);});
 await test(label+' revision holds only increment over approved main, applies once and frees decrease after approval',async()=>{const year=await quota(),wf=await start({neededDate:year+'-06-15'});assert.equal((await budgets.availability({departmentId:'dept-3',year},owner)).totalHeadcount,2);await finish(wf.id);await resubmit(wf.id,{headcount:4});let usage=await budgets.availability({departmentId:'dept-3',year},owner);assert.equal(usage.usedHeadcount,2);assert.equal(usage.reservedHeadcount,2);assert.equal(usage.totalHeadcount,4);assert.equal((await reqs.getRequisitionById(wf.requisitionId)).headcount,2);await finish(wf.id);usage=await budgets.availability({departmentId:'dept-3',year},owner);assert.equal(usage.usedHeadcount,4);assert.equal(usage.reservedHeadcount,0);await resubmit(wf.id,{headcount:1});assert.equal((await budgets.availability({departmentId:'dept-3',year},owner)).totalHeadcount,4);await finish(wf.id);assert.equal((await budgets.availability({departmentId:'dept-3',year},owner)).totalHeadcount,1);});
 for(const action of ['REJECT','REQUEST_INFO'])await test(label+' '+action+' releases revision increment while retaining previously approved main',async()=>{const year=await quota(),wf=await start({neededDate:year+'-06-15'});await finish(wf.id);await resubmit(wf.id,{headcount:4});await decide(wf.id,action,'Financial correction');const usage=await budgets.availability({departmentId:'dept-3',year},hr);assert.equal(usage.totalHeadcount,2);assert.equal(usage.reservedHeadcount,0);assert.equal((await reqs.getRequisitionById(wf.requisitionId)).headcount,2);});
 await test(label+' rejected first round and never-approved CLOSED consume no used quota',async()=>{const year=await quota(),wf=await start({neededDate:year+'-06-15'});await decide(wf.id,'REJECT','Rejected before approval');assert.equal((await budgets.availability({departmentId:'dept-3',year},hr)).totalHeadcount,0);await reqs.updateRequisition(wf.requisitionId,{status:'CLOSED'},hr);assert.equal((await budgets.availability({departmentId:'dept-3',year},hr)).totalHeadcount,0);const id=await create({neededDate:year+'-06-15'});await reqs.updateRequisition(id,{status:'CLOSED'},hr);assert.equal((await budgets.availability({departmentId:'dept-3',year},hr)).totalHeadcount,0);});
 await test(label+' approved and previously held CLOSED retains annual used quota',async()=>{const year=await quota(),wf=await start({neededDate:year+'-06-15'});await finish(wf.id);await reqs.updateRequisition(wf.requisitionId,{status:'CLOSED'},hr);assert.equal((await budgets.availability({departmentId:'dept-3',year},hr)).totalHeadcount,2);});
 await test(label+' transfer department and year recalculates reservations without changing effective data early',async()=>{const year=await quota(),otherYear=year+100;await quota(10,1000000,'dept-4',year);await quota(10,1000000,'dept-4',otherYear);const wf=await start({neededDate:year+'-06-15'});await finish(wf.id);await resubmit(wf.id,{departmentId:'dept-4'},hr);assert.equal((await budgets.availability({departmentId:'dept-3',year},hr)).usedHeadcount,2);assert.equal((await budgets.availability({departmentId:'dept-4',year},hr)).reservedHeadcount,2);await finish(wf.id);assert.equal((await budgets.availability({departmentId:'dept-3',year},hr)).totalHeadcount,0);await resubmit(wf.id,{neededDate:otherYear+'-12-15'},hr);assert.equal((await budgets.availability({departmentId:'dept-4',year:otherYear},hr)).reservedSalary,600);await finish(wf.id);assert.equal((await budgets.availability({departmentId:'dept-4',year},hr)).totalHeadcount,0);assert.equal((await budgets.availability({departmentId:'dept-4',year:otherYear},hr)).usedSalary,600);});
 await test(label+' quota decrease below effective or pending allocations is rejected with no version write',async()=>{const year=await quota(),wf=await start({neededDate:year+'-06-15'});await finish(wf.id);await resubmit(wf.id,{headcount:4});await reject(()=>budgets.save({departmentId:'dept-3',year,expectedVersion:1,approvedHeadcount:3,annualSalaryBudget:1000000},hr),'BUDGET_LIMIT_BELOW_ALLOCATED');assert.equal((await budgets.history('dept-3',year,hr)).versions.length,1);});
 await test(label+' final approval rechecks bounds and rollback preserves both budget and workflow',async()=>{const year=await quota(2),wf=await start({neededDate:year+'-06-15'});await finish(wf.id);await reject(()=>resubmit(wf.id,{headcount:4}),'HEADCOUNT_BUDGET_EXCEEDED');await budgets.confirm({requisitionId:wf.requisitionId,document:{headcount:4},expectedVersion:1,reason:'Budget exception for revision'},hr);await resubmit(wf.id,{headcount:4});await decide(wf.id);const before=await approvals.read(wf.id,owner),usage=await budgets.availability({departmentId:'dept-3',year},hr),prepare=db.prepare.bind(db);db.prepare=sql=>sql.startsWith('INSERT INTO requisition_approval_events')?{run:async()=>{throw Error('FINAL_EVENT_FAILURE');}}:prepare(sql);try{await assert.rejects(()=>decide(wf.id),/FINAL_EVENT_FAILURE/);}finally{db.prepare=prepare;}assert.deepEqual(await approvals.read(wf.id,owner),before);assert.deepEqual(await budgets.availability({departmentId:'dept-3',year},hr),usage);await decide(wf.id);assert.equal((await reqs.getRequisitionById(wf.requisitionId)).headcount,4);});
 await test(label+' final approval blocks an exception whose authorized excess is no longer sufficient',async()=>{const year=await quota(1),id=await create({status:'DRAFT',neededDate:year+'-06-15'});await budgets.confirm({requisitionId:id,expectedVersion:1,reason:'One additional hire'},hr);await reqs.updateRequisition(id,{status:'OPEN'},owner);const wf=await approvals.submit(id,{requestId:key()},owner);await decide(wf.id);const other=await create({status:'DRAFT',neededDate:year+'-06-15',headcount:1});await budgets.confirm({requisitionId:other,expectedVersion:1,reason:'Another specific exception'},hr);await reqs.updateRequisition(other,{status:'OPEN'},owner);const before=await approvals.read(wf.id,owner);await reject(()=>decide(wf.id),'HEADCOUNT_BUDGET_EXCEEDED');assert.deepEqual(await approvals.read(wf.id,owner),before);await budgets.confirm({requisitionId:id,expectedVersion:1,reason:'Reconfirm aggregate excess'},hr);await decide(wf.id);assert.equal((await approvals.read(wf.id,owner)).status,'APPROVED');});
 await test(label+' retry and concurrent resubmission reserve one revision and restart at first level',async()=>{const year=await quota(),wf=await start({neededDate:year+'-06-15'});await finish(wf.id);const detail=await approvals.read(wf.id,owner),payload={requestId:key(),expectedVersion:detail.version,expectedDocumentHash:detail.editVersion,document:{headcount:4}},results=await Promise.all([approvals.resubmit(wf.id,payload,owner),approvals.resubmit(wf.id,payload,owner)]);assert.deepEqual(results[0],results[1]);assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM headcount_budget_reservations WHERE requisition_id=?').get(wf.requisitionId)).n,1);assert.equal((await budgets.availability({departmentId:'dept-3',year},hr)).totalHeadcount,4);const tracking=await approvals.tracking(wf.requisitionId,owner);assert.equal(tracking.rounds.length,2);assert.equal(tracking.rounds[1].steps[0].status,'PENDING');});
 await test(label+' unapproved correction reserves new quantity once rather than old main plus revision',async()=>{const year=await quota(),wf=await start({neededDate:year+'-06-15',headcount:4});await decide(wf.id,'REQUEST_INFO','Reduce planned recruitment');await resubmit(wf.id,{headcount:1});assert.equal((await budgets.availability({departmentId:'dept-3',year},hr)).totalHeadcount,1);assert.equal((await reqs.getRequisitionById(wf.requisitionId)).headcount,4);await finish(wf.id);assert.equal((await budgets.availability({departmentId:'dept-3',year},hr)).usedHeadcount,1);});
 await test(label+' outside department and role scope deny budget data and writes',async()=>{const year=await quota(10,1000000,'dept-2');await reject(()=>budgets.availability({departmentId:'dept-2',year},owner),'BUDGET_OUT_OF_SCOPE');for(const user of [s.users.APPROVER,s.users.RECRUITER,s.users.INTERVIEWER,s.users.CANDIDATE])await reject(()=>budgets.list(user,year),'BUDGET_FORBIDDEN');await reject(()=>budgets.save({departmentId:'dept-3',year,approvedHeadcount:5,annualSalaryBudget:1000000},owner),'BUDGET_FORBIDDEN');});
 await test(label+' flag OFF preserves legacy behavior and does not auto-enable budget checking',async()=>{config.HEADCOUNT_BUDGET_ENABLED=false;try{const result=await reqs.createRequisition({title:'Legacy compatibility',departmentId:'dept-3',hiringManagerId:owner.id},owner);assert.equal(result.success,true);}finally{config.HEADCOUNT_BUDGET_ENABLED=true;}});
}
async function apiFrontend(app,s){const config=require('../src/config/config');config.REQUISITION_APPROVAL_ENABLED=true;const sessions={};for(const [role,email]of Object.entries({ADMIN:'admin@company.com',HR_MANAGER:'hrmanager@company.com',HIRING_MGR:'hiringmgr@company.com',APPROVER:'approver@company.com',CANDIDATE:'candidate@example.com'}))sessions[role]=await app.login(email);const {createFrontendRuntime}=require('./helpers/frontendRuntime'),runtime=await createFrontendRuntime(app.base,'/login');runtime.nodes.get('email').value='hiringmgr@company.com';runtime.nodes.get('password').value='Ats@123456';await runtime.nodes.get('login-form').dispatch('submit');await runtime.settle();
 if(mode==='s3-03'){
  const wf=await s.start();await s.decide(wf.id,'APPROVE','A recorded decision');
  await test('HTTP tracking anonymous/outside/nonexistent/mutation protection',async()=>{const url='/requisition-approvals/by-requisition/'+wf.requisitionId;assert.equal((await app.api('GET',url)).status,401);assert.equal((await app.api('GET',url,sessions.CANDIDATE.token)).status,403);for(const method of ['PUT','DELETE'])assert.equal((await app.api(method,url,sessions.ADMIN.token,{})).status,404);const foreign=await s.create({departmentId:'dept-2'},s.admin);assert.equal((await app.api('GET','/requisition-approvals/by-requisition/'+foreign,sessions.HIRING_MGR.token)).status,403);assert.equal((await app.api('GET','/requisition-approvals/by-requisition/missing',sessions.ADMIN.token)).status,404);});
  await test('real frontend detail integrates current ordered chain, person, time and comment',async()=>{await vm.runInContext('openRequisitionDetails('+JSON.stringify(wf.requisitionId)+')',runtime.context);await runtime.settle();const panel=runtime.nodes.get('s303-s210');assert.equal(panel.classList.contains('hidden'),false);const flatten=node=>node.textContent+' '+node.children.map(flatten).join(' '),text=flatten(panel);assert.match(text,/Theo dõi phê duyệt/);assert.match(text,/A recorded decision/);assert.match(text,/Đã duyệt/);assert.match(text,/Đang chờ cấp 2/);assert.equal(panel.querySelectorAll('[data-step-id]').length,2);});
  await test('frontend tracking clear on route change and no private stale content',async()=>{runtime.window.ATS_ROUTER.navigate('/dashboard');await runtime.settle();assert.equal(runtime.nodes.get('s303-s210').classList.contains('hidden'),true);assert.equal(runtime.nodes.get('s303-s210').textContent,'');assert.deepEqual(runtime.errors,[]);});
 }else{
  const year=await s.quota(2,10000);
  await test('HTTP budget role guards navigation and missing reason match business rules',async()=>{const uri='/headcount-budgets?year='+year;assert.equal((await app.api('GET',uri)).status,401);assert.equal((await app.api('GET',uri,sessions.CANDIDATE.token)).status,403);assert.equal((await app.api('GET',uri,sessions.HIRING_MGR.token)).status,200);for(const role of ['ADMIN','HR_MANAGER','HIRING_MGR'])assert.ok((await app.api('GET','/navigation/menu',sessions[role].token)).data.menuItems.some(item=>item.path==='/admin/headcount-budgets'));const draft=await s.create({neededDate:year+'-06-15',status:'DRAFT',headcount:3});assert.equal((await app.api('POST','/headcount-budgets/exceptions',sessions.HIRING_MGR.token,{requisitionId:draft,expectedVersion:1,reason:'No privilege'})).status,403);assert.equal((await app.api('POST','/headcount-budgets/exceptions',sessions.HR_MANAGER.token,{requisitionId:draft,expectedVersion:1,reason:''})).status,400);assert.equal((await app.api('PUT','/requisitions/'+draft,sessions.HIRING_MGR.token,{status:'OPEN'})).data.code,'HEADCOUNT_BUDGET_EXCEEDED');});
  await test('real frontend new request shows server-derived quota and recomputes year/month/cost',async()=>{await vm.runInContext('openCreateReqModal()',runtime.context);runtime.nodes.get('create-req-dept-input').value='dept-3';runtime.nodes.get('create-req-headcount-input').value='3';runtime.nodes.get('create-req-salary-max-input').value='300';runtime.nodes.get('create-req-needed-date-input').value=year+'-12-15';await runtime.window.ATS_HEADCOUNT_BUDGET_UI.preview('create');assert.match(runtime.nodes.get('s304-create-message').textContent,/Còn 2 headcount/);assert.match(runtime.nodes.get('s304-create-message').textContent,/1 tháng: 900/);assert.match(runtime.nodes.get('s304-create-message').textContent,/Vượt chỉ tiêu/);assert.equal(runtime.nodes.get('s304-create-override').classList.contains('hidden'),true);});
  await test('HR frontend manages versioned quota and sees immutable financial history',async()=>{await runtime.nodes.get('logout-btn').dispatch('click');runtime.nodes.get('email').value='hrmanager@company.com';runtime.nodes.get('password').value='Ats@123456';await runtime.nodes.get('login-form').dispatch('submit');await runtime.settle();runtime.window.ATS_ROUTER.navigate('/admin/headcount-budgets');await runtime.settle();runtime.nodes.get('s304-year').value=String(year);await runtime.window.ATS_HEADCOUNT_BUDGET_UI.load();runtime.nodes.get('s304-department').value='dept-3';await runtime.window.ATS_HEADCOUNT_BUDGET_UI.details();runtime.nodes.get('s304-headcount').value='5';runtime.nodes.get('s304-salary').value='20000';runtime.nodes.get('s304-change-reason').value='HR updated plan';await runtime.nodes.get('s304-form').dispatch('submit');await runtime.settle();assert.equal((await s.budgets.current('dept-3',year)).version_number,2);assert.match(runtime.nodes.get('s304-history').textContent,/HR updated plan/);assert.deepEqual(runtime.errors,[]);});
 }
}
async function main(){const config=require('../src/config/config');config.HEADCOUNT_BUDGET_ENABLED=false;const app=await openApplication();try{const s=await setup(app.db,'SQLite');if(mode==='s3-03')await trackingCases(s,'SQLite');else await budgetCases(s,'SQLite');await apiFrontend(app,s);}finally{await app.close();}config.HEADCOUNT_BUDGET_ENABLED=false;
 const {PGlite}=require('@electric-sql/pglite'),{PostgresDatabase,pgTypes}=require('../src/db/postgres'),engine=new PGlite();let tail=Promise.resolve();const query=async(sql,params)=>{const result=params===undefined?(await engine.exec(sql)).at(-1):await engine.query(sql,params);return{rows:(result?.rows||[]).map(row=>Object.fromEntries(Object.entries(row).map(([key,value])=>{const type=result.fields.find(field=>field.name===key)?.dataTypeID;return[key,value instanceof Date?(type===1082?value.toISOString().slice(0,10):value.toISOString()):typeof value==='bigint'?Number(value):typeof value==='string'&&[20,1700].includes(type)?pgTypes().getTypeParser(type)(value):value];}))),rowCount:result?.affectedRows||result?.rows?.length||0};};const db=new PostgresDatabase({},{on(){},query,async connect(){const previous=tail;let release;tail=new Promise(resolve=>release=resolve);await previous;return{query,release};},async end(){await engine.close();}});try{await require('../src/db/migrate-postgres').migrate(db);await db.transaction(()=>require('../src/db/seed').seedDatabase(db));const s=await setup(db,'PostgreSQL embedded');if(mode==='s3-03')await trackingCases(s,'PostgreSQL embedded');else await budgetCases(s,'PostgreSQL embedded');}finally{await db.close();}console.log((mode==='s3-03'?'S303':'S304')+'_RESULT '+JSON.stringify({passed,failed,total:passed+failed}));process.exitCode=failed?1:0;}
main().catch(error=>{console.error(error.stack);process.exitCode=1;});
