const crypto=require('node:crypto'),Rbac=require('../middlewares/rbacMiddleware'),{ApprovalConfigurationError}=require('./approvalConfigurationService');
class HeadcountBudgetError extends ApprovalConfigurationError {}
class HeadcountBudgetService {
 static enabled(){return require('../config/config').HEADCOUNT_BUDGET_ENABLED===true;}
 constructor(db){this.db=db;this.rbac=new Rbac(db);}
 fail(code,message,status=409){throw new HeadcountBudgetError(code,message,status);}
 async actor(user,permission){const actor=await this.rbac.getAuthorizedActor(user?.id,permission);if(!actor)this.fail('BUDGET_FORBIDDEN','Bạn không có quyền thực hiện thao tác ngân sách này.',403);return actor;}
 async scope(departmentId,user){if(typeof departmentId!=='string'||!departmentId.trim())this.fail('INVALID_BUDGET_DEPARTMENT','Cần mã phòng ban hợp lệ.',400);const department=await this.db.prepare('SELECT id,name,manager_id,status FROM departments WHERE id=?').get(departmentId);if(!department||department.status!=='ACTIVE')this.fail('INVALID_BUDGET_DEPARTMENT','Phòng ban không tồn tại hoặc không hoạt động.',400);if(!user.roles.some(role=>['ADMIN','HR_MANAGER'].includes(role))&&(!user.roles.includes('HIRING_MGR')||department.manager_id!==user.id))this.fail('BUDGET_OUT_OF_SCOPE','Ngân sách phòng ban này không thuộc phạm vi quản lý của bạn.',403);return department;}
 year(value){const year=Number(value);if(!Number.isSafeInteger(year)||year<1000||year>9999)this.fail('INVALID_BUDGET_YEAR','Năm ngân sách không hợp lệ.',400);return year;}
 document(doc){const date=doc.neededDate;if(typeof date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date+'T00:00:00Z'))||new Date(date+'T00:00:00Z').toISOString().slice(0,10)!==date)this.fail('BUDGET_DOCUMENT_INCOMPLETE','Cần ngày cần người hợp lệ để xác định năm ngân sách.',400);
  if(!['number','string'].includes(typeof doc.headcount)||!['number','string'].includes(typeof doc.proposedSalaryMax))this.fail('BUDGET_DOCUMENT_INCOMPLETE','Số lượng và lương đề xuất phải là số hợp lệ.',400);
  const headcount=Number(doc.headcount),salary=Number(doc.proposedSalaryMax),year=this.year(date.slice(0,4)),months=13-Number(date.slice(5,7)),cost=Math.ceil(headcount*salary*months);
  if(typeof doc.departmentId!=='string'||!doc.departmentId.trim()||!Number.isSafeInteger(headcount)||headcount<1||headcount>2147483647||doc.proposedSalaryMax==null||doc.proposedSalaryMax===''||!Number.isFinite(salary)||salary<0||!Number.isSafeInteger(cost))this.fail('BUDGET_DOCUMENT_INCOMPLETE','Cần phòng ban, số lượng và lương đề xuất hợp lệ để kiểm tra ngân sách.',400);
  return {departmentId:doc.departmentId,year,headcount,proposedSalaryMax:salary,neededDate:date,months,annualCost:cost};
 }
 hash(doc){const value=this.document(doc);return crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');}
 async lock(keys){if(this.db.provider==='postgres')for(const key of [...new Set(keys)].sort())await this.db.prepare('SELECT pg_advisory_xact_lock(hashtext(?))').get('headcount-budget:'+key);}
 async current(departmentId,year,required=true){const row=await this.db.prepare('SELECT b.id,b.department_id,b.budget_year,v.id AS version_id,v.version_number,v.approved_headcount,v.annual_salary_budget FROM headcount_budgets b JOIN headcount_budget_versions v ON v.id=b.current_version_id WHERE b.department_id=? AND b.budget_year=?').get(departmentId,year);if(!row&&required)this.fail('HEADCOUNT_BUDGET_UNAVAILABLE','Chưa có chỉ tiêu và ngân sách lương cho phòng ban/năm này. Cần HR Manager hoặc Admin cấu hình.');return row;}
 async main(id){if(typeof id!=='string'||!id.trim())this.fail('BUDGET_DOCUMENT_INCOMPLETE','Cần mã yêu cầu hợp lệ.',400);const row=await this.db.prepare('SELECT id,department_id,headcount,proposed_salary_max,needed_date,status FROM requisitions WHERE id=?').get(id);if(!row)this.fail('REQUISITION_NOT_FOUND','Không tìm thấy yêu cầu tuyển dụng.',404);return {id:row.id,departmentId:row.department_id,headcount:row.headcount,proposedSalaryMax:row.proposed_salary_max,neededDate:row.needed_date,status:row.status};}
 async measure(departmentId,year,excludeId=''){
  const first=year+'-01-01',last=year+'-12-31';
  const rows=await this.db.prepare("SELECT r.id,r.department_id,r.headcount,r.proposed_salary_max,r.needed_date,r.status,w.status AS workflow_status,p.approved,x.replaces_unapproved FROM requisitions r LEFT JOIN requisition_approval_workflows w ON w.requisition_id=r.id LEFT JOIN headcount_budget_participation p ON p.requisition_id=r.id LEFT JOIN headcount_budget_reservations x ON x.requisition_id=r.id AND x.submission_id=w.current_submission_id AND w.status='PENDING' WHERE r.department_id=? AND r.needed_date>=? AND r.needed_date<=? AND r.status IN ('OPEN','IN_PROGRESS','CLOSED') AND r.id<>? ORDER BY r.id").all(departmentId,first,last,excludeId);
  const approvals=await this.db.prepare("SELECT w.requisition_id,e.response_json FROM requisition_approval_events e JOIN requisition_approval_workflows w ON w.id=e.workflow_id JOIN requisitions r ON r.id=w.requisition_id WHERE e.action='APPROVE' AND r.department_id=? AND r.needed_date>=? AND r.needed_date<=?").all(departmentId,first,last);
  const approved=new Set(approvals.filter(row=>JSON.parse(row.response_json).status==='APPROVED').map(row=>row.requisition_id));let headcount=0,salary=0;
  for(const row of rows){if(row.replaces_unapproved)continue;if(row.status==='CLOSED'&&(!row.approved||!approved.has(row.id)))continue;if(row.workflow_status==='REJECTED'&&!approved.has(row.id))continue;const value=this.document({departmentId:row.department_id,headcount:row.headcount,proposedSalaryMax:row.proposed_salary_max,neededDate:row.needed_date});headcount+=value.headcount;salary+=value.annualCost;}
  const pending=await this.db.prepare("SELECT x.headcount_delta,x.salary_delta FROM headcount_budget_reservations x JOIN requisition_approval_workflows w ON w.requisition_id=x.requisition_id AND w.current_submission_id=x.submission_id JOIN requisitions r ON r.id=x.requisition_id WHERE x.department_id=? AND x.budget_year=? AND w.status='PENDING' AND r.status IN ('OPEN','IN_PROGRESS') AND x.requisition_id<>?").all(departmentId,year,excludeId);
  const reservedHeadcount=pending.reduce((sum,row)=>sum+Number(row.headcount_delta),0),reservedSalary=pending.reduce((sum,row)=>sum+Number(row.salary_delta),0);
  if(!Number.isSafeInteger(headcount+reservedHeadcount)||!Number.isSafeInteger(salary+reservedSalary))this.fail('BUDGET_AMOUNT_OVERFLOW','Dữ liệu ngân sách vượt giới hạn số an toàn.',400);
  return {usedHeadcount:headcount,usedSalary:salary,reservedHeadcount,reservedSalary,totalHeadcount:headcount+reservedHeadcount,totalSalary:salary+reservedSalary};
 }
 async everApproved(id){const row=await this.db.prepare('SELECT approved FROM headcount_budget_participation WHERE requisition_id=?').get(id);if(row?.approved)return true;const events=await this.db.prepare("SELECT e.response_json FROM requisition_approval_events e JOIN requisition_approval_workflows w ON w.id=e.workflow_id WHERE w.requisition_id=? AND e.action='APPROVE'").all(id);return events.some(event=>JSON.parse(event.response_json).status==='APPROVED');}
 async projection(doc,requisitionId=null,pending=false){const value=this.document(doc),budget=await this.current(value.departmentId,value.year),others=await this.measure(value.departmentId,value.year,requisitionId||'');let contributionHeadcount=value.headcount,contributionSalary=value.annualCost;
  if(pending&&requisitionId&&await this.everApproved(requisitionId)){const original=await this.main(requisitionId);if(original.neededDate&&original.proposedSalaryMax!=null){const base=this.document(original);if(base.departmentId===value.departmentId&&base.year===value.year){contributionHeadcount=Math.max(base.headcount,value.headcount);contributionSalary=Math.max(base.annualCost,value.annualCost);}}}
  const headcountAfter=others.totalHeadcount+contributionHeadcount,salaryAfter=others.totalSalary+contributionSalary;
  return {...value,...others,budgetId:budget.id,versionId:budget.version_id,version:Number(budget.version_number),approvedHeadcount:Number(budget.approved_headcount),annualSalaryBudget:Number(budget.annual_salary_budget),remainingHeadcount:Number(budget.approved_headcount)-others.totalHeadcount,remainingSalary:Number(budget.annual_salary_budget)-others.totalSalary,headcountAfter,salaryAfter,headcountOver:Math.max(0,headcountAfter-Number(budget.approved_headcount)),salaryOver:Math.max(0,salaryAfter-Number(budget.annual_salary_budget)),contentHash:this.hash(doc)};
 }
 async enforce(doc,requisitionId,pending=false){const plan=await this.projection(doc,requisitionId,pending);if(plan.headcountOver||plan.salaryOver){const exception=await this.db.prepare('SELECT id FROM headcount_budget_exceptions WHERE requisition_id=? AND version_id=? AND content_hash=? AND headcount_over>=? AND salary_over>=? ORDER BY created_at DESC,id LIMIT 1').get(requisitionId,plan.versionId,plan.contentHash,plan.headcountOver,plan.salaryOver);if(!exception)this.fail('HEADCOUNT_BUDGET_EXCEEDED','Vượt chỉ tiêu headcount hoặc ngân sách lương. Cần HR Manager/Admin xác nhận ngoại lệ kèm lý do.');}return plan;}
 async locksFor(doc,id){const keys=[];const value=this.document(doc);keys.push(value.departmentId+':'+value.year);if(id){const previous=await this.main(id);if(previous.neededDate&&previous.proposedSalaryMax!=null){const base=this.document(previous);keys.push(base.departmentId+':'+base.year);}}await this.lock(keys);}
 async effective(id,approved=false){return this.db.transaction(async()=>{const doc=await this.main(id);if(doc.status==='DRAFT')return;await this.locksFor(doc,id);const plan=await this.enforce(doc,id);await this.db.prepare('INSERT INTO headcount_budget_participation(requisition_id,approved) VALUES (?,?) ON CONFLICT(requisition_id) DO NOTHING').run(id,this.db.provider==='postgres'?approved:Number(approved));if(approved)await this.db.prepare('UPDATE headcount_budget_participation SET approved=TRUE WHERE requisition_id=?').run(id);return plan;});}
 async reserve(id,doc,submissionId){return this.db.transaction(async()=>{await this.locksFor(doc,id);const plan=await this.enforce(doc,id,true),original=await this.main(id);const replacesUnapproved=!await this.everApproved(id);let baseHeadcount=0,baseSalary=0;if(!replacesUnapproved&&original.neededDate&&original.proposedSalaryMax!=null){const base=this.document(original);if(base.departmentId===plan.departmentId&&base.year===plan.year){baseHeadcount=base.headcount;baseSalary=base.annualCost;}}
  await this.db.prepare('INSERT INTO headcount_budget_reservations(requisition_id,department_id,budget_year,headcount_delta,salary_delta,replaces_unapproved,content_hash,submission_id) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(requisition_id) DO UPDATE SET department_id=excluded.department_id,budget_year=excluded.budget_year,headcount_delta=excluded.headcount_delta,salary_delta=excluded.salary_delta,replaces_unapproved=excluded.replaces_unapproved,content_hash=excluded.content_hash,submission_id=excluded.submission_id').run(id,plan.departmentId,plan.year,Math.max(0,plan.headcount-baseHeadcount),Math.max(0,plan.annualCost-baseSalary),this.db.provider==='postgres'?replacesUnapproved:Number(replacesUnapproved),plan.contentHash,submissionId);return plan;});}
 async release(id){await this.db.prepare('DELETE FROM headcount_budget_reservations WHERE requisition_id=?').run(id);}
 async final(id,doc){await this.locksFor(doc,id);return this.enforce(doc,id,false);}
 async markApproved(id){await this.db.prepare('INSERT INTO headcount_budget_participation(requisition_id,approved) VALUES (?,TRUE) ON CONFLICT(requisition_id) DO UPDATE SET approved=TRUE').run(id);await this.release(id);}
 async availability(data,user){return this.db.transaction(async()=>{user=await this.actor(user,'headcount_budget.read');await this.scope(data.departmentId,user);const year=this.year(data.year||data.neededDate?.slice(0,4));if(data.year&&data.neededDate&&Number(data.neededDate.slice(0,4))!==year)this.fail('INVALID_BUDGET_YEAR','Năm ngân sách phải khớp ngày cần người.',400);await this.lock([data.departmentId+':'+year]);const budget=await this.current(data.departmentId,year,false);if(!budget)return {configured:false,departmentId:data.departmentId,year};const used=await this.measure(data.departmentId,year);let projection=null;if(data.headcount!=null&&data.headcount!==''&&data.proposedSalaryMax!=null&&data.proposedSalaryMax!==''&&data.neededDate){if(data.requisitionId){const original=await this.main(data.requisitionId);await this.scope(original.departmentId,user);}projection=await this.projection(data,data.requisitionId||null,true);}return {configured:true,departmentId:data.departmentId,year,version:Number(budget.version_number),approvedHeadcount:Number(budget.approved_headcount),annualSalaryBudget:Number(budget.annual_salary_budget),...used,remainingHeadcount:Number(budget.approved_headcount)-used.totalHeadcount,remainingSalary:Number(budget.annual_salary_budget)-used.totalSalary,projection};});}
 async list(user,year){user=await this.actor(user,'headcount_budget.read');year=this.year(year);const manager=user.roles.some(role=>['ADMIN','HR_MANAGER'].includes(role));return this.db.prepare('SELECT b.id,b.department_id AS "departmentId",d.name AS "departmentName",b.budget_year AS year,v.version_number AS version,v.approved_headcount AS "approvedHeadcount",v.annual_salary_budget AS "annualSalaryBudget" FROM headcount_budgets b JOIN departments d ON d.id=b.department_id JOIN headcount_budget_versions v ON v.id=b.current_version_id WHERE b.budget_year=?'+(manager?'':' AND d.manager_id=?')+' ORDER BY d.name,b.id').all(year,...(manager?[]:[user.id]));}
 async save(data,user){return this.db.transaction(async()=>{user=await this.actor(user,'headcount_budget.manage');if(!user.roles.some(role=>['ADMIN','HR_MANAGER'].includes(role)))this.fail('BUDGET_FORBIDDEN','Chỉ HR Manager/Admin được quản lý chỉ tiêu.',403);await this.scope(data.departmentId,user);const year=this.year(data.year),headcount=Number(data.approvedHeadcount),salary=Number(data.annualSalaryBudget);if([data.approvedHeadcount,data.annualSalaryBudget].some(value=>value==null||value===''||!['number','string'].includes(typeof value)))this.fail('INVALID_BUDGET_LIMIT','Cần nhập đầy đủ chỉ tiêu và ngân sách.',400);if(!Number.isSafeInteger(headcount)||headcount<0||headcount>2147483647||!Number.isSafeInteger(salary)||salary<0)this.fail('INVALID_BUDGET_LIMIT','Chỉ tiêu và ngân sách phải là số nguyên không âm trong giới hạn an toàn.',400);await this.lock([data.departmentId+':'+year]);const current=await this.current(data.departmentId,year,false);if(current&&data.expectedVersion!==Number(current.version_number))this.fail('BUDGET_VERSION_CONFLICT','Ngân sách đã thay đổi. Vui lòng tải lại.');if(!current&&data.expectedVersion!=null)this.fail('BUDGET_VERSION_CONFLICT','Ngân sách không còn khớp phiên bản yêu cầu.');const used=await this.measure(data.departmentId,year);if(headcount<used.totalHeadcount||salary<used.totalSalary)this.fail('BUDGET_LIMIT_BELOW_ALLOCATED','Không được giảm chỉ tiêu/ngân sách xuống dưới mức đã phân bổ và đang giữ.');const id=current?.id||'hcb-'+crypto.randomUUID(),versionId='hbv-'+crypto.randomUUID(),version=current?Number(current.version_number)+1:1;if(!current)await this.db.prepare('INSERT INTO headcount_budgets(id,department_id,budget_year) VALUES (?,?,?)').run(id,data.departmentId,year);await this.db.prepare('INSERT INTO headcount_budget_versions(id,budget_id,version_number,approved_headcount,annual_salary_budget,actor_id,actor_name,reason) VALUES (?,?,?,?,?,?,?,?)').run(versionId,id,version,headcount,salary,user.id,user.fullName||user.id,typeof data.reason==='string'?data.reason.trim():null);await this.db.prepare('UPDATE headcount_budgets SET current_version_id=? WHERE id=?').run(versionId,id);return {id,departmentId:data.departmentId,year,version,approvedHeadcount:headcount,annualSalaryBudget:salary};});}
 async confirm(data,user){return this.db.transaction(async()=>{user=await this.actor(user,'headcount_budget.override');if(!user.roles.some(role=>['ADMIN','HR_MANAGER'].includes(role)))this.fail('BUDGET_FORBIDDEN','Chỉ HR Manager/Admin được xác nhận ngoại lệ.',403);if(typeof data.reason!=='string'||!data.reason.trim()||data.reason.length>4000)this.fail('BUDGET_EXCEPTION_REASON_REQUIRED','Ngoại lệ phải có lý do không rỗng, tối đa 4000 ký tự.',400);const original=await this.main(data.requisitionId);if(!['DRAFT','OPEN'].includes(original.status))this.fail('REQUISITION_EDIT_STATE_FORBIDDEN','Trạng thái yêu cầu không cho phép xác nhận ngoại lệ.');const doc={...original,...data.document};await this.scope(doc.departmentId,user);await this.locksFor(doc,original.id);const plan=await this.projection(doc,original.id,true);if(data.expectedVersion!==plan.version)this.fail('BUDGET_VERSION_CONFLICT','Ngân sách đã thay đổi. Vui lòng tải lại.');if(!plan.headcountOver&&!plan.salaryOver)this.fail('BUDGET_EXCEPTION_NOT_NEEDED','Hồ sơ chưa vượt chỉ tiêu hoặc ngân sách.',400);const id='hbe-'+crypto.randomUUID();await this.db.prepare('INSERT INTO headcount_budget_exceptions(id,requisition_id,department_id,budget_year,version_id,content_hash,headcount_over,salary_over,confirmed_by,confirmed_name,reason) VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(id,original.id,plan.departmentId,plan.year,plan.versionId,plan.contentHash,plan.headcountOver,plan.salaryOver,user.id,user.fullName||user.id,data.reason.trim());return {id,requisitionId:original.id,version:plan.version,headcountOver:plan.headcountOver,salaryOver:plan.salaryOver};});}
 async history(departmentId,year,user){user=await this.actor(user,'headcount_budget.read');await this.scope(departmentId,user);year=this.year(year);return {versions:await this.db.prepare('SELECT v.version_number AS version,v.approved_headcount AS "approvedHeadcount",v.annual_salary_budget AS "annualSalaryBudget",v.actor_id AS "actorId",v.actor_name AS "actorName",v.reason,v.created_at AS "createdAt" FROM headcount_budget_versions v JOIN headcount_budgets b ON b.id=v.budget_id WHERE b.department_id=? AND b.budget_year=? ORDER BY v.version_number').all(departmentId,year),exceptions:await this.db.prepare('SELECT e.id,e.requisition_id AS "requisitionId",e.headcount_over AS "headcountOver",e.salary_over AS "salaryOver",e.confirmed_by AS "confirmedBy",e.confirmed_name AS "confirmedName",e.reason,e.created_at AS "createdAt",v.version_number AS "budgetVersion",v.approved_headcount AS "approvedHeadcount",v.annual_salary_budget AS "annualSalaryBudget" FROM headcount_budget_exceptions e JOIN headcount_budget_versions v ON v.id=e.version_id WHERE e.department_id=? AND e.budget_year=? ORDER BY e.created_at,e.id').all(departmentId,year)};}
}
module.exports={HeadcountBudgetService,HeadcountBudgetError};
