const Rbac=require('../middlewares/rbacMiddleware'),{ApprovalConfigurationError}=require('./approvalConfigurationService');
class RequisitionTrackingService {
 constructor(db){this.db=db;}
 fail(code,message){throw new ApprovalConfigurationError(code,message,400);}
 day(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value)||Number(value.slice(0,4))<1000||!Number.isFinite(Date.parse(value+'T00:00:00Z'))||new Date(value+'T00:00:00Z').toISOString().slice(0,10)!==value)this.fail('INVALID_REQUISITION_DATE_FILTER','Khoảng ngày tạo không hợp lệ.');return value;}
 businessDate(timestamp){if(!timestamp)return null;const raw=typeof timestamp==='string'?timestamp.trim():String(timestamp),instant=new Date(raw.replace(' ','T')+(/(?:Z|[+-]\d\d:\d\d)$/i.test(raw)?'':'Z'));if(!Number.isFinite(instant.getTime()))return null;return new(require('./requisitionService'))(this.db).businessDate(instant);}
 normalize(options){const value={...options};for(const key of ['departmentId','recruiterId'])if(value[key]!=null&&value[key]!==''&&typeof value[key]!=='string')this.fail('INVALID_REQUISITION_FILTER','Bộ lọc không hợp lệ.');if(value.createdFrom)value.createdFrom=this.day(value.createdFrom);if(value.createdTo)value.createdTo=this.day(value.createdTo);if(value.createdFrom&&value.createdTo&&value.createdFrom>value.createdTo)this.fail('INVALID_REQUISITION_DATE_FILTER','Ngày bắt đầu phải trước hoặc bằng ngày kết thúc.');if(value.status&&!['ALL','DRAFT','OPEN','IN_PROGRESS','CLOSED','PAUSED','CANCELLED'].includes(value.status))this.fail('INVALID_REQUISITION_STATUS_FILTER','Trạng thái lọc không hợp lệ.');if(value.page!=null||value.limit!=null){value.page=Number(value.page??1);value.limit=Number(value.limit??20);if(!Number.isSafeInteger(value.page)||value.page<1||!Number.isSafeInteger(value.limit)||value.limit<1||value.limit>100)this.fail('INVALID_REQUISITION_PAGINATION','Trang và kích thước trang không hợp lệ.');}return value;}
 filters(conditions,params,options){if(options.departmentId){conditions.push('r.department_id=?');params.push(options.departmentId);}if(options.recruiterId){conditions.push('(r.recruiter_id=? OR EXISTS(SELECT 1 FROM requisition_recruiter_supports filter_support WHERE filter_support.requisition_id=r.id AND filter_support.user_id=?))');params.push(options.recruiterId,options.recruiterId);}if(options.createdFrom){conditions.push(this.db.provider==='postgres'?'r.created_at>=?':'julianday(r.created_at)>=julianday(?)');params.push(options.createdFrom+'T00:00:00+07:00');}if(options.createdTo){conditions.push(this.db.provider==='postgres'?"r.created_at < (?::timestamptz + INTERVAL '24 hours')":'julianday(r.created_at)<julianday(?)+1');params.push(options.createdTo+'T00:00:00+07:00');}}
 metrics(row,now=new Date()){const service=new(require('./requisitionService'))(this.db),today=service.businessDate(now),closed=['CLOSED','CANCELLED'].includes(row.status),start=row.status==='DRAFT'?null:this.businessDate(row.opened_at||row.created_at),end=closed?this.businessDate(row.lifecycle_end||row.updated_at):today,needed=row.needed_date?String(row.needed_date):null,diff=(a,b)=>Math.round((Date.parse(a+'T00:00:00Z')-Date.parse(b+'T00:00:00Z'))/86400000),daysOpen=start&&end?Math.max(0,diff(end,start)):null,daysRemaining=needed&&/^\d{4}-\d{2}-\d{2}$/.test(needed)&&Number.isFinite(Date.parse(needed+'T00:00:00Z'))&&new Date(needed+'T00:00:00Z').toISOString().slice(0,10)===needed?diff(needed,today):null;return{businessDate:today,openedAt:row.opened_at||null,daysOpen,daysOpenEstimated:row.status!=='DRAFT'&&(!row.opened_at||closed&&!row.lifecycle_end),daysRemaining,overdue:['OPEN','IN_PROGRESS'].includes(row.status)&&daysRemaining!=null&&daysRemaining<0,paused:row.status==='PAUSED'};}
 async supports(ids){if(!ids.length)return new Map();const rows=await this.db.prepare('SELECT s.requisition_id,u.id,u.full_name AS name FROM requisition_recruiter_supports s JOIN users u ON u.id=s.user_id WHERE s.requisition_id IN ('+ids.map(()=>'?').join(',')+') ORDER BY s.requisition_id,u.full_name,u.id').all(...ids),groups=new Map();for(const row of rows){const members=groups.get(row.requisition_id)||[];members.push({id:row.id,name:row.name});groups.set(row.requisition_id,members);}return groups;}
 async options(user){const actor=await new Rbac(this.db).getAuthorizedActor(user?.id,'requisition.read');if(!actor)throw new ApprovalConfigurationError('REQUISITION_TRACKING_FORBIDDEN','Bạn không có quyền xem danh sách yêu cầu.',403);const result=await new(require('./requisitionService'))(this.db).getRequisitions({viewer:actor,viewerId:actor.id,approvalEnabled:require('../config/config').REQUISITION_APPROVAL_ENABLED}),departments=new Map(),recruiters=new Map();for(const item of result.requisitions){if(item.departmentId)departments.set(item.departmentId,{id:item.departmentId,name:item.departmentName});if(item.recruiter)recruiters.set(item.recruiter.id,{id:item.recruiter.id,name:item.recruiter.fullName});for(const user of item.supportRecruiters||[])recruiters.set(user.id,user);}const sort=rows=>[...rows.values()].sort((a,b)=>a.name.localeCompare(b.name,'vi')||a.id.localeCompare(b.id));return{departments:sort(departments),recruiters:sort(recruiters),recruiterScope:'PRIMARY_OR_SUPPORT',timeField:'createdAt',timeZone:'Asia/Ho_Chi_Minh'};}
}
module.exports=RequisitionTrackingService;
