const crypto=require('node:crypto'),Rbac=require('../middlewares/rbacMiddleware'),Requisitions=require('./requisitionService'),Approvals=require('./requisitionApprovalService'),{HeadcountBudgetService:Budgets}=require('./headcountBudgetService'),Postings=require('./jobPostingService'),{ApprovalConfigurationError}=require('./approvalConfigurationService');
class RequisitionLifecycleError extends ApprovalConfigurationError {}
class RequisitionLifecycleService {
 constructor(db){this.db=db;this.rbac=new Rbac(db);this.requisitions=new Requisitions(db);this.budgets=new Budgets(db);}
 fail(code,message,status=409){throw new RequisitionLifecycleError(code,message,status);}
 async actor(user,permission){const actor=await this.rbac.getAuthorizedActor(user?.id,permission);if(!actor)this.fail('LIFECYCLE_FORBIDDEN','Bạn không có quyền thực hiện thao tác vòng đời yêu cầu tuyển dụng.',403);return actor;}
 async read(id,user){const item=await this.requisitions.getRequisitionById(id),access=await this.requisitions.requisitionAccess(item,user,false,true);if(!access.success)this.fail(access.code,access.message,access.statusCode);return item;}
 async lock(key){if(this.db.provider==='postgres')await this.db.prepare('SELECT pg_advisory_xact_lock(hashtext(?))').get('requisition-lifecycle:'+key);}
 async pipeline(id,locked=false){return this.db.prepare("SELECT id,full_name AS \"fullName\",stage FROM candidates WHERE requisition_id=? ORDER BY id"+(locked&&this.db.provider==='postgres'?' FOR UPDATE':'')).all(id);}
 async context(id,user){return this.db.transaction(async()=>{user=await this.actor(user,'requisition.read');const item=await this.read(id,user),version=(await this.db.prepare('SELECT version FROM requisition_lifecycle_state WHERE requisition_id=?').get(id))?.version||0,pipeline=await this.pipeline(id),workflow=await this.db.prepare('SELECT status FROM requisition_approval_workflows WHERE requisition_id=?').get(id),history=await this.db.prepare('SELECT id,version,before_status,after_status,action,reason,actor_id,actor_name,created_at,budget_json,postings_json FROM requisition_lifecycle_events WHERE requisition_id=? ORDER BY version').all(id),manager=user.roles.some(role=>['ADMIN','HR_MANAGER'].includes(role))&&await this.rbac.hasPermission(user.id,'requisition.lifecycle.manage');return{requisitionId:id,status:item.status,version,canManage:manager,allowedActions:manager?(['OPEN','IN_PROGRESS'].includes(item.status)?['FULFILLED','PAUSED','CANCELLED']:item.status==='PAUSED'?['FULFILLED','CANCELLED']:item.status==='DRAFT'?['CANCELLED']:[]):[],pendingApproval:workflow?.status==='PENDING',outstanding:pipeline.filter(row=>!['HIRED','REJECTED'].includes(row.stage)),hiredCount:pipeline.filter(row=>row.stage==='HIRED').length,history:history.map(({budget_json,postings_json,...event})=>({...event,budget:JSON.parse(budget_json),postings:JSON.parse(postings_json)}))};});}
 async transition(id,data,user){if(!data||typeof data!=='object'||Array.isArray(data)||typeof data.requestId!=='string'||!data.requestId.trim()||data.requestId.length>128)this.fail('LIFECYCLE_REQUEST_ID_REQUIRED','Thiếu mã chống gửi trùng hợp lệ.',400);if(!['FULFILLED','PAUSED','CANCELLED'].includes(data.action))this.fail('INVALID_LIFECYCLE_ACTION','Thao tác vòng đời không hợp lệ.',400);if(typeof data.reason!=='string'||!data.reason.trim()||data.reason.length>4000)this.fail('LIFECYCLE_REASON_REQUIRED','Vui lòng nhập lý do cụ thể, tối đa 4000 ký tự.',400);if(!Number.isSafeInteger(data.expectedVersion)||data.expectedVersion<0)this.fail('LIFECYCLE_EXPECTATION_REQUIRED','Thiếu phiên bản yêu cầu cần cập nhật.',400);
  return this.db.transaction(async()=>{user=await this.actor(user,'requisition.lifecycle.manage');if(!user.roles.some(role=>['ADMIN','HR_MANAGER'].includes(role)))this.fail('LIFECYCLE_FORBIDDEN','Chỉ HR Manager/Admin được quản lý vòng đời yêu cầu tuyển dụng.',403);await this.lock('request:'+user.id+':'+data.requestId);const fingerprint=new Approvals(this.db).fingerprint('LIFECYCLE',id,data),receipt=await this.db.prepare('SELECT fingerprint,response_json FROM requisition_lifecycle_events WHERE actor_id=? AND request_id=?').get(user.id,data.requestId);if(receipt){if(receipt.fingerprint!==fingerprint)this.fail('LIFECYCLE_RETRY_CONFLICT','Mã thao tác đã được dùng cho dữ liệu khác.');await this.read(id,user);return JSON.parse(receipt.response_json);}
  const approvals=new Approvals(this.db);await approvals.lock('requisition:'+id);const workflow=await this.db.prepare('SELECT id FROM requisition_approval_workflows WHERE requisition_id=?').get(id);if(workflow)await approvals.lock('workflow:'+workflow.id);await this.db.prepare('SELECT id FROM requisitions WHERE id=?'+(this.db.provider==='postgres'?' FOR UPDATE':'')).get(id);const item=await this.read(id,user),version=(await this.db.prepare('SELECT version FROM requisition_lifecycle_state WHERE requisition_id=?').get(id))?.version||0;if(version!==data.expectedVersion)this.fail('LIFECYCLE_STALE','Yêu cầu đã thay đổi. Vui lòng tải lại.');const target={FULFILLED:'CLOSED',PAUSED:'PAUSED',CANCELLED:'CANCELLED'}[data.action];if(item.status===target)return{changed:false,requisitionId:id,status:target,version};if(!(['OPEN','IN_PROGRESS'].includes(item.status)||item.status==='PAUSED'&&data.action!=='PAUSED'||item.status==='DRAFT'&&data.action==='CANCELLED'))this.fail('LIFECYCLE_STATE_FORBIDDEN','Trạng thái hiện tại không cho phép thao tác này.');
  const currentWorkflow=await this.db.prepare('SELECT status FROM requisition_approval_workflows WHERE requisition_id=?').get(id);if(data.action!=='PAUSED'&&currentWorkflow?.status==='PENDING')this.fail('LIFECYCLE_PENDING_APPROVAL','Cần xử lý xong workflow hoặc revision đang chờ phê duyệt trước khi đóng/huỷ.');const pipeline=await this.pipeline(id,true),outstanding=pipeline.filter(row=>!['HIRED','REJECTED'].includes(row.stage)),hired=pipeline.filter(row=>row.stage==='HIRED').length;if(data.action!=='PAUSED'&&outstanding.length)this.fail('LIFECYCLE_PIPELINE_UNRESOLVED','Còn '+outstanding.length+' ứng viên trong pipeline cần xử lý trước khi đóng/huỷ.');const approved=await this.budgets.everApproved(id);if(data.action==='FULFILLED'&&!approved)this.fail('LIFECYCLE_APPROVAL_REQUIRED','Chỉ được xác nhận đã tuyển đủ sau khi quantity được phê duyệt.');if(data.action==='CANCELLED'&&hired&&!approved)this.fail('LIFECYCLE_APPROVAL_REQUIRED','Có ứng viên đã tuyển; cần quantity được phê duyệt trước khi huỷ.');if(data.action==='CANCELLED'&&hired>Number(item.headcount))this.fail('LIFECYCLE_HIRED_QUANTITY_INVALID','Số ứng viên đã tuyển vượt quantity được duyệt. Cần xử lý dữ liệu trước khi huỷ.');
  const reservations=await this.db.prepare('SELECT submission_id,department_id,budget_year,headcount_delta,salary_delta FROM headcount_budget_reservations WHERE requisition_id=? ORDER BY submission_id').all(id);let budget={reservationsBefore:reservations,action:data.action,retainedHeadcount:data.action==='CANCELLED'?hired:item.headcount,expectedSalaryBudget:null};if(data.action!=='CANCELLED'&&item.neededDate&&item.proposedSalaryMax!=null){const value=this.budgets.document(item);budget={...budget,departmentId:value.departmentId,year:value.year,neededDate:value.neededDate,proposedSalaryMax:value.proposedSalaryMax,months:value.months,expectedSalaryBudget:value.annualCost};}if(data.action==='CANCELLED'){if(hired){const value=this.budgets.document(item);budget={...budget,departmentId:value.departmentId,year:value.year,neededDate:value.neededDate,proposedSalaryMax:value.proposedSalaryMax,months:value.months,approvedQuantity:value.headcount,expectedSalaryBudget:Math.ceil(hired*value.proposedSalaryMax*value.months)};}else budget={...budget,departmentId:item.departmentId,year:item.neededDate?Number(item.neededDate.slice(0,4)):null,expectedSalaryBudget:0};}
  if(Budgets.enabled()&&item.neededDate&&item.proposedSalaryMax!=null)await this.budgets.locksFor(item,id);const postings=await new Postings(this.db).hide(id,data.action,{actor:user,reason:data.reason}),eventId='rle-'+crypto.randomUUID(),result={changed:true,requisitionId:id,status:target,version:version+1,eventId};await this.db.prepare("UPDATE requisitions SET status=?,updated_at=datetime('now') WHERE id=?").run(target,id);if(data.action==='CANCELLED')await this.budgets.release(id);await this.db.prepare('INSERT INTO requisition_lifecycle_events(id,requisition_id,version,before_status,after_status,action,reason,actor_id,actor_name,request_id,fingerprint,pipeline_json,budget_json,postings_json,response_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(eventId,id,result.version,item.status,target,data.action,data.reason.trim(),user.id,user.fullName||user.id,data.requestId,fingerprint,JSON.stringify(pipeline),JSON.stringify(budget),JSON.stringify(postings),JSON.stringify(result));await this.db.prepare('INSERT INTO requisition_lifecycle_state(requisition_id,version,last_event_id) VALUES (?,?,?) ON CONFLICT(requisition_id) DO UPDATE SET version=excluded.version,last_event_id=excluded.last_event_id').run(id,result.version,eventId);return result;
  });
 }
}
module.exports={RequisitionLifecycleService,RequisitionLifecycleError};
