const {HeadcountBudgetError}=require('../services/headcountBudgetService');
class HeadcountBudgetController {
 constructor(service,rbac,auth){this.service=service;this.rbac=rbac;this.auth=auth;}
 async handle(req,res,url,parseBody){const send=(status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(data));};const parts=url.pathname.slice('/api/v1/headcount-budgets'.length).split('/').filter(Boolean),permission=req.method==='POST'?(parts[0]==='exceptions'?'headcount_budget.override':'headcount_budget.manage'):'headcount_budget.read',user=await this.rbac.authorize(req,res,this.auth,permission);if(!user)return;
  try{const body=async()=>{const value=await parseBody(req);if(!value||typeof value!=='object'||Array.isArray(value))throw new HeadcountBudgetError('INVALID_BUDGET_REQUEST','Dữ liệu ngân sách phải là đối tượng hợp lệ.',400);return value;};let data,status=200;if(req.method==='GET'&&parts[0]==='availability')data=await this.service.availability(Object.fromEntries(url.searchParams),user);else if(req.method==='GET'&&parts[0]==='history')data=await this.service.history(url.searchParams.get('departmentId'),url.searchParams.get('year'),user);else if(req.method==='GET'&&parts[0]==='options'){const fresh=await this.service.actor(user,'headcount_budget.read');data=await this.service.db.prepare("SELECT id,name FROM departments WHERE status='ACTIVE'"+(fresh.roles.some(role=>['ADMIN','HR_MANAGER'].includes(role))?'':' AND manager_id=?')+' ORDER BY name,id').all(...(fresh.roles.some(role=>['ADMIN','HR_MANAGER'].includes(role))?[]:[fresh.id]));}else if(req.method==='GET'&&!parts.length)data=await this.service.list(user,url.searchParams.get('year'));else if(req.method==='POST'&&!parts.length){data=await this.service.save(await body(),user);status=201;}else if(req.method==='POST'&&parts[0]==='exceptions'&&parts.length===1){data=await this.service.confirm(await body(),user);status=201;}else{send(404,{success:false,code:'BUDGET_ENDPOINT_NOT_FOUND',message:'Không tìm thấy thao tác ngân sách.'});return;}send(status,{success:true,data});}
  catch(error){if(error instanceof HeadcountBudgetError)send(error.statusCode,{success:false,code:error.code,message:error.message});else if(error.message==='Invalid JSON')send(400,{success:false,code:'BAD_REQUEST',message:'Dữ liệu không hợp lệ.'});else send(500,{success:false,code:'BUDGET_INTERNAL_ERROR',message:'Không thể xử lý ngân sách. Vui lòng thử lại.'});}
 }
}
module.exports=HeadcountBudgetController;
